# shopify/metafields_api.py
"""
MVQueen Shopify Metafield Sync
------------------------------

Handles metafield-only updates for Shopify products using the
safe ShopifyAPI wrapper.

This allows:
- Refreshing metafields without touching product data
- Patching metafields
- Bulk metafield updates
"""

from typing import Dict, Any
from shopify.api import ShopifyAPI


def sync_metafields(product_id: str, metafields: Dict[str, Any]) -> Dict[str, Any]:
    """
    Syncs metafields for a Shopify product.

    Args:
        product_id: Shopify product ID
        metafields: Dict of metafields generated by MVQueen

    Returns:
        Dict with Shopify API response.
    """

    api = ShopifyAPI()
    response = api.update_metafields(product_id, metafields)

    return {
        "metafield_sync_response": response,
        "metafields": metafields,
    }


__all__ = ["sync_metafields"]