# mvqueen_engine/brand_brain/brand_banks/skincare_banks.py
"""
Skincare vocabulary banks for the MVQueen Omniluxe Engine.

Used for:
- Skincare product descriptions
- Ingredient-driven editorial
- Benefit-focused copy
- Persona voice for skincare items
- SEO and metafield generation

All vocab is women-centered, modern, elevated, and rooted in
MVQueen's luxury-hybrid editorial tone.
"""

SKIN_TYPES = [
    "ultra_dry_skin", "extremely_dry_skin", "deeply_dehydrated_skin", "surface_dehydrated_skin",
    "oil_starved_skin", "moisture_starved_skin", "lipid_deficient_skin", "fragile_dry_skin",
    "flushed_sensitive_skin", "easily_triggered_skin", "reactive_redness_skin", "flare_prone_skin",
    "oily_shine_zone_skin", "oily_all_over_skin", "persistent_oily_skin", "high_sebum_skin",
    "combination_shift_oily_skin", "combination_shift_dry_skin", "combination_balanced_tone_skin", "combination_dynamic_skin",

    "barrier_fragile_skin", "barrier_thin_skin", "barrier_delicate_skin", "barrier_vulnerable_skin",
    "barrier_strengthening_needed_skin", "barrier_repair_priority_skin", "barrier_sensitive_oily_skin", "barrier_sensitive_dry_skin",
    "barrier_sensitive_combination_skin", "barrier_sensitive_normal_skin", "barrier_sensitive_mature_skin", "barrier_sensitive_acne_skin",
    "oil_resistant_surface_skin", "oil_absorbing_surface_skin", "oil_reactive_surface_skin", "oil_flaring_skin",
    "oil_spiking_skin", "oil_fluctuating_skin", "oil_unbalanced_skin", "oil_overproduction_skin",

    "hydration_loss_skin", "hydration_compromised_skin", "hydration_fragile_skin", "hydration_thirsty_skin",
    "hydration_rebound_skin", "hydration_sensitive_skin", "hydration_priority_skin", "hydration_low_skin",
    "hydration_flat_skin", "hydration_dull_skin", "hydration_weak_skin", "hydration_needy_skin",
    "moisture_loss_skin", "moisture_compromised_skin", "moisture_fragile_skin", "moisture_thirsty_skin",
    "moisture_rebound_skin", "moisture_sensitive_skin", "moisture_priority_skin", "moisture_low_skin",

    "texture_rough_skin", "texture_bumpy_skin", "texture_irregular_skin", "texture_coarse_skin",
    "texture_softening_needed_skin", "texture_refinement_needed_skin", "texture_smoothing_needed_skin", "texture_balancing_skin",
    "texture_sensitive_dry_skin", "texture_sensitive_oily_skin", "texture_sensitive_combination_skin", "texture_sensitive_mature_skin",
    "tone_uneven_skin", "tone_dull_skin", "tone_flat_skin", "tone_shadowed_skin",
    "tone_brightening_needed_skin", "tone_balancing_needed_skin", "tone_smoothing_needed_skin", "tone_refining_needed_skin",

    "hyperpigmentation_sensitive_skin", "dark_spot_sensitive_skin", "post_acne_mark_skin", "post_inflammation_mark_skin",
    "melanin_rich_oily_skin", "melanin_rich_dry_skin", "melanin_rich_sensitive_skin", "melanin_rich_combination_skin",
    "melanin_rich_balanced_skin", "melanin_rich_mature_skin", "melanin_rich_acne_prone_skin", "melanin_rich_glow_seeking_skin",
    "sun_reactive_skin", "sun_sensitive_dry_skin", "sun_sensitive_oily_skin", "sun_sensitive_combination_skin",
    "sun_sensitive_mature_skin", "sun_sensitive_sensitive_skin", "sun_sensitive_balanced_skin", "sun_sensitive_glow_seeking_skin",

    "heat_sensitive_oily_skin", "heat_sensitive_dry_skin", "heat_sensitive_combination_skin", "heat_sensitive_sensitive_skin",
    "cold_sensitive_oily_skin", "cold_sensitive_dry_skin", "cold_sensitive_combination_skin", "cold_sensitive_sensitive_skin",
    "wind_sensitive_dry_skin", "wind_sensitive_oily_skin", "wind_sensitive_combination_skin", "wind_sensitive_sensitive_skin",
    "humidity_reactive_oily_skin", "humidity_reactive_dry_skin", "humidity_reactive_combination_skin", "humidity_reactive_sensitive_skin",
    "dry_climate_sensitive_skin", "humid_climate_sensitive_skin", "urban_environment_sensitive_skin", "pollution_reactive_skin",

    "mature_dull_skin", "mature_dehydrated_skin", "mature_oil_balanced_skin", "mature_oil_unbalanced_skin",
    "mature_sensitive_oily_skin", "mature_sensitive_dry_skin", "mature_sensitive_combination_skin", "mature_sensitive_balanced_skin",
    "aging_texture_skin", "aging_tone_skin", "aging_firmness_skin", "aging_elasticity_skin",
    "aging_dry_skin", "aging_oily_skin", "aging_combination_skin", "aging_sensitive_skin",
    "aging_balanced_skin", "aging_glow_seeking_skin", "aging_smoothness_seeking_skin", "aging_brightness_seeking_skin",

    "acne_prone_mature_skin", "acne_prone_sensitive_skin", "acne_prone_dry_skin", "acne_prone_oily_skin",
    "acne_prone_combination_skin", "acne_prone_balanced_skin", "acne_prone_hormonal_skin", "acne_prone_stress_skin",
    "blemish_sensitive_skin", "blemish_reactive_skin", "blemish_flare_skin", "blemish_mark_prone_skin",
    "clog_prone_sensitive_skin", "clog_prone_dry_skin", "clog_prone_oily_skin", "clog_prone_combination_skin",
    "blackhead_sensitive_skin", "whitehead_sensitive_skin", "pore_expanded_skin", "pore_clogging_risk_skin",

    "post_treatment_dry_skin", "post_treatment_oily_skin", "post_treatment_sensitive_skin", "post_treatment_combination_skin",
    "post_exfoliation_dry_skin", "post_exfoliation_sensitive_skin", "post_exfoliation_oily_skin", "post_exfoliation_combination_skin",
    "post_retinol_dry_skin", "post_retinol_sensitive_skin", "post_retinol_oily_skin", "post_retinol_combination_skin",
    "post_shave_sensitive_skin", "post_shave_dry_skin", "post_shave_oily_skin", "post_shave_combination_skin",
    "post_sun_exposure_skin", "post_heat_exposure_skin", "post_cold_exposure_skin", "post_stress_exposure_skin"
    "normal_skin", "dry_skin", "oily_skin", "combination_skin",
    "sensitive_skin", "balanced_normal_skin", "dehydrated_dry_skin", "flaky_dry_skin",
    "tight_dry_skin", "glow_seeking_dry_skin", "shine_prone_oily_skin", "congested_oily_skin",
    "breakout_prone_oily_skin", "matte_preferred_oily_skin", "t_zone_oily_combination_skin", "u_zone_dry_combination_skin",
    "balanced_combination_skin", "reactive_sensitive_skin", "redness_prone_sensitive_skin", "barrier_compromised_sensitive_skin",

    "normal_to_dry_skin", "normal_to_oily_skin", "dry_to_sensitive_skin", "oily_to_sensitive_skin",
    "combination_to_sensitive_skin", "hydration_seeking_skin", "oil_balancing_skin", "barrier_supporting_skin",
    "calming_needed_skin", "soothing_needed_skin", "comfort_seeking_skin", "radiance_seeking_skin",
    "texture_refining_skin", "pore_visible_oily_skin", "dull_dry_skin", "parched_dry_skin",
    "overactive_oily_skin", "shine_control_skin", "matte_finish_preferred_skin", "dewy_finish_preferred_skin",

    "satin_finish_preferred_skin", "natural_finish_preferred_skin", "lightweight_texture_preferred_skin", "rich_texture_preferred_skin",
    "gel_texture_preferred_skin", "cream_texture_preferred_skin", "balm_texture_preferred_skin", "water_based_preferred_skin",
    "oil_based_preferred_skin", "fragrance_sensitive_skin", "ingredient_sensitive_skin", "retinol_sensitive_skin",
    "acne_prone_oily_skin", "acne_prone_combination_skin", "acne_prone_sensitive_skin", "blemish_prone_skin",
    "clog_prone_skin", "blackhead_prone_skin", "whitehead_prone_skin", "pore_clogging_sensitive_skin",

    "rosacea_prone_skin", "eczema_prone_skin", "psoriasis_prone_skin", "dermatitis_prone_skin",
    "inflamed_sensitive_skin", "irritation_prone_skin", "heat_sensitive_skin", "cold_sensitive_skin",
    "environmentally_sensitive_skin", "pollution_sensitive_skin", "humidity_reactive_skin", "dry_climate_reactive_skin",
    "oily_t_zone_skin", "dry_cheek_zone_skin", "balanced_t_zone_skin", "balanced_cheek_zone_skin",
    "oily_forehead_skin", "oily_nose_skin", "oily_chin_skin", "dry_under_eye_skin",

    "dry_mouth_area_skin", "dry_jawline_skin", "oily_jawline_skin", "combination_patchy_skin",
    "combination_balanced_skin", "combination_shift_skin", "seasonally_dry_skin", "seasonally_oily_skin",
    "seasonally_sensitive_skin", "seasonally_combination_skin", "hormonal_oily_skin", "hormonal_dry_skin",
    "hormonal_sensitive_skin", "hormonal_acne_prone_skin", "stress_reactive_skin", "stress_sensitive_skin",
    "fatigue_dull_skin", "fatigue_sensitive_skin", "fatigue_oily_skin", "fatigue_dry_skin",

    "mature_dry_skin", "mature_oily_skin", "mature_sensitive_skin", "mature_combination_skin",
    "aging_concerned_skin", "fine_line_prone_skin", "wrinkle_prone_skin", "elasticity_concerned_skin",
    "firmness_seeking_skin", "plumpness_seeking_skin", "youthful_finish_preferred_skin", "smooth_finish_preferred_skin",
    "glass_skin_goal_skin", "velvet_skin_goal_skin", "matte_skin_goal_skin", "glowy_skin_goal_skin",
    "radiant_skin_goal_skin", "soft_focus_skin_goal_skin", "even_tone_goal_skin", "brightening_goal_skin",

    "hyperpigmentation_prone_skin", "dark_spot_prone_skin", "uneven_texture_skin", "rough_texture_skin",
    "bumpy_texture_skin", "keratosis_prone_skin", "texture_sensitive_skin", "tone_sensitive_skin",
    "hydration_loss_prone_skin", "oil_loss_prone_skin", "barrier_weakened_skin", "barrier_strong_skin",
    "barrier_repair_needed_skin", "barrier_protection_needed_skin", "moisture_seeking_skin", "oil_control_seeking_skin",
    "clarity_seeking_skin", "smoothness_seeking_skin", "softness_seeking_skin", "comfort_seeking_dry_skin",

    "cooling_preferred_skin", "warming_preferred_skin", "soothing_preferred_skin", "nourishing_preferred_skin",
    "balancing_preferred_skin", "refining_preferred_skin", "purifying_preferred_skin", "hydrating_preferred_skin",
    "mattifying_preferred_skin", "brightening_preferred_skin", "firming_preferred_skin", "plumping_preferred_skin",
    "calming_preferred_skin", "strengthening_preferred_skin", "revitalizing_preferred_skin", "rejuvenating_preferred_skin",
    "smoothing_preferred_skin", "softening_preferred_skin", "glow_preferred_skin", "matte_preferred_skin",

    "oil_resistant_skin", "oil_responsive_skin", "hydration_responsive_skin", "ingredient_responsive_skin",
    "climate_responsive_skin", "season_responsive_skin", "stress_responsive_skin", "hormone_responsive_skin",
    "sweat_prone_oily_skin", "sweat_prone_sensitive_skin", "sweat_prone_combination_skin", "heat_reactive_oily_skin",
    "cold_reactive_dry_skin", "wind_sensitive_skin", "sun_sensitive_skin", "uv_sensitive_skin",
    "post_treatment_sensitive_skin", "post_exfoliation_sensitive_skin", "post_retinol_sensitive_skin", "post_shave_sensitive_skin"
]

SKINCARE_TEXTURES = [
    "gel-like",
    "silky",
    "cushiony",
    "whipped",
    "cloud-soft",
    "weightless",
    "balmy",
    "milky",
    "velvety",
]

SKINCARE_BENEFITS = [
    "hydrating",
    "brightening",
    "firming",
    "smoothing",
    "plumping",
    "softening",
    "barrier-strengthening",
    "radiance-boosting",
    "calming",
]

SKINCARE_ACTIVES = [
    "hyaluronic acid",
    "niacinamide",
    "vitamin C",
    "retinol",
    "peptides",
    "ceramides",
    "AHAs",
    "BHAs",
    "squalane",
]

SKIN_GOALS = [
    "glass skin",
    "radiant skin",
    "even tone",
    "refined texture",
    "deep hydration",
    "visible firmness",
    "calm clarity",
]

SKIN_CONCERNS = [
    "dryness",
    "dullness",
    "texture",
    "fine lines",
    "uneven tone",
    "sensitivity",
    "dehydration",
]

SKIN_INGREDIENTS = [
    "hyaluronic_acid", "niacinamide", "retinol", "retinaldehyde",
    "bakuchiol", "vitamin_c", "ascorbic_acid", "magnesium_ascorbyl_phosphate",
    "sodium_ascorbyl_phosphate", "tetrahexyldecyl_ascorbate", "vitamin_e", "tocopherol",
    "ceramides", "ceramide_np", "ceramide_ap", "ceramide_eop",
    "squalane", "squalene", "glycerin", "panthenol",
    "allantoin", "aloe_vera", "centella_asiatica", "madecassoside",

    "salicylic_acid", "glycolic_acid", "lactic_acid", "mandelic_acid",
    "azelaic_acid", "kojic_acid", "tranexamic_acid", "gluconolactone",
    "lactobionic_acid", "polyglutamic_acid", "beta_glucan", "urea",
    "zinc_pca", "copper_peptides", "matrixyl", "argireline",
    "peptide_complex", "amino_acids", "collagen", "elastin",

    "shea_butter", "cocoa_butter", "mango_butter", "jojoba_oil",
    "rosehip_oil", "marula_oil", "argan_oil", "hemp_seed_oil",
    "evening_primrose_oil", "sunflower_seed_oil", "olive_squalane", "apricot_kernel_oil",
    "grapeseed_oil", "avocado_oil", "camellia_oil", "meadowfoam_seed_oil",
    "ceramide_complex", "fatty_acids", "linoleic_acid", "oleic_acid",

    "green_tea_extract", "chamomile_extract", "licorice_root_extract", "cica_extract",
    "algae_extract", "sea_kelp_extract", "rose_extract", "lavender_extract",
    "calendula_extract", "turmeric_extract", "ginger_extract", "ginseng_extract",
    "pomegranate_extract", "blueberry_extract", "raspberry_extract", "blackberry_extract",
    "cucumber_extract", "oat_extract", "rice_extract", "soy_extract",

    "dimethicone", "cyclopentasiloxane", "cyclohexasiloxane", "silicone_elastomers",
    "isohexadecane", "caprylic_capric_triglyceride", "cetyl_alcohol", "stearyl_alcohol",
    "cetearyl_alcohol", "behenyl_alcohol", "propylene_glycol", "butylene_glycol",
    "pentylene_glycol", "hexylene_glycol", "polysorbate_20", "polysorbate_60",
    "polysorbate_80", "carbomer", "xanthan_gum", "hydroxyethylcellulose",

    "titanium_dioxide", "zinc_oxide", "avobenzone", "octocrylene",
    "homosalate", "octisalate", "oxybenzone", "ensulizole",
    "tinosorb_s", "tinosorb_m", "mexoryl_xl", "mexoryl_sx",
    "iron_oxides", "mica", "silica", "boron_nitride",
    "synthetic_fluorphlogopite", "bismuth_oxychloride", "kaolin_clay", "bentonite_clay",

    "ferulic_acid", "resveratrol", "coenzyme_q10", "astaxanthin",
    "alpha_lipoic_acid", "glutathione", "superoxide_dismutase", "niacin",
    "biotin", "folic_acid", "vitamin_k", "vitamin_b12",
    "vitamin_b5", "vitamin_b3", "vitamin_b6", "vitamin_b1",
    "vitamin_b2", "vitamin_d3", "vitamin_a_palmitate", "retinyl_palmitate",

    "tea_tree_oil", "peppermint_oil", "eucalyptus_oil", "rosemary_oil",
    "bergamot_oil", "ylang_ylang_oil", "jasmine_oil", "rose_oil",
    "orange_peel_oil", "lemon_peel_oil", "grapefruit_oil", "mandarin_oil",
    "cedarwood_oil", "patchouli_oil", "sandalwood_oil", "vanilla_extract",
    "fragrance", "essential_oils", "aroma_compounds", "botanical_blend",

    "niacinamide_complex", "peptide_blend", "ceramide_blend", "antioxidant_blend",
    "hydration_complex", "brightening_complex", "soothing_complex", "barrier_complex",
    "ferment_filtrate", "galactomyces_ferment", "bifida_ferment", "yeast_extract",
    "probiotic_complex", "prebiotic_complex", "postbiotic_complex", "enzyme_complex",
    "papaya_enzyme", "pineapple_enzyme", "pumpkin_enzyme", "bromelain"
    "willow_bark_extract", "licorice_brightening_complex", "mulberry_extract", "bearberry_extract",
    "arbutin", "alpha_arbutin", "beta_arbutin", "tranexamic_complex",
    "azelaic_derivative", "kojic_dipalmate", "vitamin_c_ester", "ascorbyl_glucoside",
    "ascorbyl_tetraisopalmitate", "ascorbyl_phosphate_blend", "vitamin_c_complex", "vitamin_c_cocktail",
    "niacinamide_boost", "niacinamide_10_percent", "niacinamide_20_percent", "niacinamide_complex_plus",

    "retinol_microdose", "retinol_encapsulated", "retinol_slow_release", "retinol_complex",
    "retinal_encapsulated", "retinal_complex", "retinoid_blend", "granactive_retinoid",
    "adapalene_derivative", "retinyl_acetate", "retinyl_propionate", "retinyl_retinoate",
    "peptide_signal_complex", "peptide_firming_complex", "peptide_repair_complex", "peptide_lifting_complex",
    "collagen_peptides", "elastin_peptides", "tri_peptide_complex", "tetra_peptide_complex",

    "ceramide_1", "ceramide_2", "ceramide_3", "ceramide_6",
    "ceramide_rich_complex", "ceramide_repair_complex", "ceramide_strength_complex", "ceramide_barrier_complex",
    "cholesterol", "phytosphingosine", "fatty_alcohols", "fatty_acid_complex",
    "omega_3_fatty_acids", "omega_6_fatty_acids", "omega_9_fatty_acids", "omega_blend",
    "lipid_complex", "lipid_repair_complex", "lipid_barrier_complex", "lipid_softening_complex",

    "jojoba_ester", "rosehip_seed_extract", "marula_seed_extract", "argan_kernel_extract",
    "hemp_seed_extract", "evening_primrose_extract", "sunflower_extract", "olive_leaf_extract",
    "apricot_extract", "grapeseed_extract", "avocado_extract", "camellia_extract",
    "meadowfoam_extract", "black_currant_seed_oil", "cranberry_seed_oil", "blue_tansy_oil",
    "tamanu_oil", "kukui_nut_oil", "baobab_oil", "prickly_pear_seed_oil",

    "green_tea_polyphenols", "egcg", "white_tea_extract", "rooibos_extract",
    "matcha_extract", "coffeeberry_extract", "caffeine", "caffeine_complex",
    "centella_extract", "asiaticoside", "madecassic_acid", "asiatic_acid",
    "algae_bioferment", "kelp_bioferment", "spirulina_extract", "chlorella_extract",
    "sea_mineral_complex", "marine_collagen", "marine_ferment", "marine_actives",

    "turmeric_root_extract", "curcumin", "ginger_root_extract", "ginseng_root_extract",
    "holy_basil_extract", "ashwagandha_extract", "licorice_root_ferment", "mushroom_extract",
    "reishi_extract", "shiitake_extract", "chaga_extract", "snow_mushroom_extract",
    "oat_beta_glucan", "colloidal_oatmeal", "rice_bran_extract", "rice_ferment",
    "soy_ferment", "soy_isoflavones", "pomegranate_enzymes", "papaya_enzymes",

    "dimethicone_crosspolymer", "silicone_blur_complex", "silicone_smoothing_complex", "silicone_film_former",
    "isohexadecane_blend", "caprylyl_glycol", "ethylhexylglycerin", "cetearyl_olivate",
    "sorbitan_olivate", "glyceryl_stearate", "glyceryl_oleate", "glyceryl_caprylate",
    "hydrogenated_polyisobutene", "hydrogenated_olive_oil", "hydrogenated_castor_oil", "hydrogenated_jojoba_oil",
    "polyacrylate_crosspolymer", "acrylates_copolymer", "carbomer_gel", "xanthan_gum_blend",

    "titanium_dioxide_coated", "zinc_oxide_micronized", "zinc_oxide_non_nano", "avobenzone_stabilized",
    "octocrylene_stabilized", "homosalate_blend", "octisalate_blend", "ensulizole_blend",
    "tinosorb_s_filter", "tinosorb_m_filter", "mexoryl_xl_filter", "mexoryl_sx_filter",
    "iron_oxide_red", "iron_oxide_yellow", "iron_oxide_black", "mica_blend",
    "silica_blur", "silica_smooth", "boron_nitride_blur", "synthetic_mica_blend",
    "hyaluronic_acid", "niacinamide", "retinol", "retinaldehyde",
    "bakuchiol", "ascorbyl_glucoside", "tetrahexyldecyl_ascorbate", "vitamin_e",
    "tocopherol_acetate", "ceramide_np", "ceramide_ap", "ceramide_eop",
    "squalane", "glycerin", "panthenol", "allantoin",
    "aloe_vera_extract", "centella_asiatica_extract", "madecassoside", "salicylic_acid",
    "glycolic_acid", "lactic_acid", "mandelic_acid", "azelaic_acid",
    "kojic_acid", "tranexamic_acid", "gluconolactone", "lactobionic_acid",
    "polyglutamic_acid", "beta_glucan", "urea", "zinc_pca",
    "copper_peptides", "matrixyl", "argireline", "peptide_complex",
    "collagen", "elastin", "shea_butter", "cocoa_butter",
    "mango_butter", "jojoba_oil", "rosehip_oil", "marula_oil",
    "argan_oil", "hemp_seed_oil", "evening_primrose_oil", "sunflower_seed_oil",
    "olive_squalane", "apricot_kernel_oil", "grapeseed_oil", "avocado_oil",
    "camellia_oil", "meadowfoam_seed_oil", "linoleic_acid", "oleic_acid",
    "green_tea_extract", "chamomile_extract", "licorice_root_extract", "cica_extract",
    "algae_extract", "sea_kelp_extract", "rose_extract", "lavender_extract",
    "calendula_extract", "turmeric_extract", "ginger_extract", "ginseng_extract",
    "pomegranate_extract", "blueberry_extract", "raspberry_extract", "blackberry_extract",
    "cucumber_extract", "oat_extract", "rice_extract", "soy_extract",
    "dimethicone", "cyclopentasiloxane", "cyclohexasiloxane", "silicone_elastomers",
    "isohexadecane", "caprylic_capric_triglyceride", "cetyl_alcohol", "stearyl_alcohol",
    "cetearyl_alcohol", "behenyl_alcohol", "propylene_glycol", "butylene_glycol",
    "pentylene_glycol", "hexylene_glycol", "polysorbate_20", "polysorbate_60",
    "polysorbate_80", "carbomer", "xanthan_gum", "hydroxyethylcellulose",
    "titanium_dioxide", "zinc_oxide", "avobenzone", "octocrylene",
    "homosalate", "octisalate", "ensulizole", "tinosorb_s",
    "tinosorb_m", "mexoryl_xl", "mexoryl_sx", "iron_oxides",
    "mica", "silica", "boron_nitride", "synthetic_fluorphlogopite",
    "kaolin_clay", "bentonite_clay", "ferulic_acid", "resveratrol",
    "coenzyme_q10", "astaxanthin", "alpha_lipoic_acid", "glutathione",
    "superoxide_dismutase", "niacin", "biotin", "folic_acid",
    "vitamin_k", "vitamin_b12", "vitamin_b5", "vitamin_b3",
    "vitamin_b6", "vitamin_b1", "vitamin_b2", "vitamin_d3",
    "retinyl_palmitate", "tea_tree_oil", "peppermint_oil", "eucalyptus_oil",
    "rosemary_oil", "bergamot_oil", "ylang_ylang_oil", "jasmine_oil",
    "orange_peel_oil", "lemon_peel_oil", "grapefruit_oil", "mandarin_oil",
    "cedarwood_oil", "patchouli_oil", "sandalwood_oil", "vanilla_extract",
    "fragrance", "essential_oils", "aroma_compounds", "botanical_blend",
    "galactomyces_ferment", "bifida_ferment", "yeast_extract", "probiotic_complex",
    "prebiotic_complex", "postbiotic_complex", "enzyme_complex", "papaya_enzyme",
    "pineapple_enzyme", "pumpkin_enzyme", "bromelain", "jojoba_esters",
    "rosehip_seed_extract", "marula_seed_extract", "argan_kernel_extract", "hemp_seed_extract",
    "evening_primrose_extract", "sunflower_extract", "olive_leaf_extract", "apricot_extract",
    "grapeseed_extract", "avocado_extract", "camellia_extract", "meadowfoam_extract",
    "black_currant_seed_oil", "cranberry_seed_oil", "blue_tansy_oil", "tamanu_oil",
    "kukui_nut_oil", "baobab_oil", "prickly_pear_seed_oil", "white_tea_extract",
    "rooibos_extract", "matcha_extract", "coffeeberry_extract", "caffeine",
    "asiaticoside", "madecassic_acid", "asiatic_acid", "algae_bioferment",
    "kelp_bioferment", "spirulina_extract", "chlorella_extract", "marine_collagen",
    "marine_ferment", "marine_actives", "turmeric_root_extract", "curcumin",
    "ginger_root_extract", "ginseng_root_extract", "holy_basil_extract", "ashwagandha_extract",
    "mushroom_extract", "reishi_extract", "shiitake_extract", "chaga_extract",
    "snow_mushroom_extract", "colloidal_oatmeal", "rice_bran_extract", "rice_ferment",
    "soy_ferment", "soy_isoflavones", "pomegranate_enzymes", "papaya_enzymes",
    "dimethicone_crosspolymer", "silicone_blur_complex", "silicone_smoothing_complex", "silicone_film_former",
    "isohexadecane_blend", "caprylyl_glycol", "ethylhexylglycerin", "cetearyl_olivate",
    "sorbitan_olivate", "glyceryl_stearate", "glyceryl_oleate", "glyceryl_caprylate",
    "hydrogenated_polyisobutene", "hydrogenated_olive_oil", "hydrogenated_castor_oil", "hydrogenated_jojoba_oil",
    "polyacrylate_crosspolymer", "acrylates_copolymer", "carbomer_gel", "xanthan_gum_blend",
    "zinc_oxide_micronized", "zinc_oxide_non_nano", "avobenzone_stabilized", "octocrylene_stabilized",
    "homosalate_blend", "octisalate_blend", "ensulizole_blend", "tinosorb_s_filter",
    "tinosorb_m_filter", "mexoryl_xl_filter", "mexoryl_sx_filter", "iron_oxide_red",
    "iron_oxide_yellow", "iron_oxide_black", "mica_blend", "silica_blur",
    "silica_smooth", "boron_nitride_blur", "synthetic_mica_blend", "kaolin_clay_purified",
    "bentonite_clay_purified", "pink_clay", "white_clay", "green_clay",
    "volcanic_ash", "charcoal_powder", "activated_charcoal", "bamboo_charcoal",
    "clay_mineral_complex", "clay_detox_complex", "clay_balancing_complex", "charcoal_detox_complex",
    "charcoal_purifying_complex", "charcoal_balancing_complex", "charcoal_clarifying_complex", "mineral_mud",
    "dead_sea_mud", "thermal_mud", "volcanic_mud", "jojoba_beads",
    "cellulose_beads", "bamboo_beads", "rice_powder", "oat_powder",
    "walnut_shell_powder", "apricot_seed_powder", "pumice_powder", "enzyme_exfoliant_blend",
    "acid_exfoliant_blend", "aha_bha_complex", "pha_complex", "glycolic_complex",
    "lactic_complex", "mandelic_complex", "salicylic_complex", "azelaic_complex",
    "brightening_acid_complex", "resurfacing_complex", "renewal_complex"
    "hydration_elixir", "moisture_elixir", "barrier_elixir", "soothing_elixir",
    "brightening_elixir", "firming_elixir", "plumping_elixir", "smoothing_elixir",
    "glow_elixir", "matte_elixir", "clarity_elixir", "radiance_elixir",
    "dew_complex", "glow_complex", "matte_complex", "soft_focus_complex",
    "skin_finish_complex", "skin_smoothing_complex", "skin_softening_complex", "skin_balancing_complex",
    "marine_actives_complex", "botanical_actives_complex", "fruit_actives_complex", "herbal_actives_complex",
    "vitamin_actives_complex", "peptide_actives_complex", "lipid_actives_complex", "enzyme_actives_complex",
    "ferment_actives_complex", "mineral_actives_complex", "antioxidant_actives_complex", "brightening_actives_complex",
    "hydrating_actives_complex", "soothing_actives_complex", "firming_actives_complex", "plumping_actives_complex",
    "renewal_actives_complex", "resurfacing_actives_complex", "clarifying_actives_complex", "balancing_actives_complex",
    "egf", "fgf", "kgf", "igf",
    "sh_polypeptide_1", "sh_polypeptide_9", "sh_polypeptide_11", "sh_polypeptide_16",
    "copper_tripeptide_1", "palmitoyl_tripeptide_5", "palmitoyl_hexapeptide_12", "acetyl_hexapeptide_8",
    "acetyl_octapeptide_3", "hexapeptide_9", "heptapeptide_15", "octapeptide_7",
    "peptide_signal_blend", "peptide_repair_blend", "peptide_firming_blend", "peptide_lifting_blend",
    "collagen_amino_acids", "elastin_amino_acids", "keratin_amino_acids", "silk_amino_acids",
    "rice_amino_acids", "soy_amino_acids", "wheat_amino_acids", "oat_amino_acids",
    "galactomyces_filtrate", "bifida_ferment_lysate", "saccharomyces_filtrate", "aspergillus_ferment",
    "lactobacillus_ferment", "bacillus_ferment", "yeast_ferment_extract", "fermented_rice_water",
    "fermented_soy_extract", "fermented_oat_extract", "fermented_barley_extract", "fermented_wheat_extract",
    "kombucha_ferment", "kimchi_ferment", "miso_ferment", "sake_ferment",
    "japanese_rice_ferment", "korean_ginseng_ferment", "green_tea_ferment", "lotus_ferment",
    "peony_extract", "sakura_extract", "yuzu_extract", "ume_extract",
    "shiso_extract", "licorice_ferment", "ginger_ferment", "turmeric_ferment",
    "marine_peptides", "seaweed_extract", "kelp_extract", "wakame_extract",
    "nori_extract", "kombu_extract", "spirulina_ferment", "chlorella_ferment",
    "marine_mineral_complex", "deep_sea_water", "thermal_water", "volcanic_water",
    "glacial_water", "alpine_water", "mineral_water_complex", "electrolyte_complex",
    "magnesium_pca", "calcium_pca", "potassium_pca", "sodium_pca",
    "zinc_gluconate", "copper_gluconate", "manganese_gluconate", "selenium_complex",
    "vitamin_c_liposomal", "vitamin_e_liposomal", "retinol_liposomal", "niacinamide_liposomal",
    "ceramide_liposomal", "peptide_liposomal", "antioxidant_liposomal", "brightening_liposomal",
    "hydrating_liposomal", "soothing_liposomal", "firming_liposomal", "plumping_liposomal",
    "resurfacing_liposomal", "renewal_liposomal", "clarifying_liposomal", "balancing_liposomal",
    "sunflower_oleosomes", "jojoba_oleosomes", "olive_oleosomes", "safflower_oleosomes",
    "liposome_delivery_system", "nanoemulsion_delivery_system", "microemulsion_delivery_system", "encapsulated_retinol",
    "encapsulated_vitamin_c", "encapsulated_niacinamide", "encapsulated_ceramides", "encapsulated_peptides",
    "encapsulated_antioxidants", "encapsulated_acids", "encapsulated_brighteners", "encapsulated_hydrators",
    "titanium_dioxide_coated", "zinc_oxide_coated", "zinc_oxide_ultrafine", "tinosorb_a2b",
    "tinosorb_hybrid", "mexoryl_eco", "bemotrizinol", "bisoctrizole",
    "octyl_triazone", "diethylamino_hydroxybenzoyl_hexyl_benzoate", "ethylhexyl_triazone", "bis_ethyloxyphenol_methoxyphenyl_triazine",
    "silica_microspheres", "silica_spheres", "silica_gel", "silica_diffusion_blend",
    "boron_nitride_spheres", "mica_spheres", "soft_focus_silica", "soft_focus_mica",
    "dimethicone_silicate", "dimethicone_vinyl_crosspolymer", "trimethylsiloxysilicate", "polymethylsilsesquioxane",
    "hd_powder_blend", "blurring_powder_blend", "soft_matting_powder", "radiance_powder",
    "film_former_complex", "longwear_polymer", "adhesion_polymer", "flexible_film_polymer",
    "gel_network_polymer", "water_gel_matrix", "oil_gel_matrix", "hydrogel_matrix",
    "lipogel_matrix", "emulsion_stabilizer", "texture_modifier", "viscosity_modifier",
    "thickening_agent", "gelling_agent", "suspending_agent", "emulsifying_agent",
    "surfactant_blend", "mild_surfactant", "amino_acid_surfactant", "sugar_surfactant",
    "cocamidopropyl_betaine", "decyl_glucoside", "lauryl_glucoside", "coco_glucoside",
    "sodium_cocoyl_isethionate", "sodium_lauroyl_methyl_ispethionate", "sodium_lauroyl_sarcosinate", "sodium_methyl_cocoyl_taurate",
    "hair_keratin", "hair_peptides", "hair_bond_repair_complex", "hair_strengthening_complex",
    "hair_smoothing_complex", "hair_shine_complex", "hair_hydration_complex", "hair_scalp_complex",
    "scalp_soothing_complex", "scalp_balancing_complex", "scalp_detox_complex", "scalp_renewal_complex",
    "body_aha_complex", "body_bha_complex", "body_urea_20", "body_urea_10",
    "body_shea_complex", "body_ceramide_complex", "body_brightening_complex", "body_firming_complex",
    "pregnancy_safe_brighteners", "pregnancy_safe_hydrators", "pregnancy_safe_lipids", "pregnancy_safe_antioxidants",
    "pregnancy_safe_exfoliants", "pregnancy_safe_ferments", "pregnancy_safe_botanicals", "pregnancy_safe_sunscreens",
    "fragrance_free_blend", "hypoallergenic_fragrance", "natural_fragrance_oils", "aroma_therapeutic_blend",
    "luxury_proprietary_complex", "signature_actives_complex", "radiance_signature_complex", "firming_signature_complex",
    "hydration_signature_complex", "barrier_signature_complex", "glow_signature_complex", "clarity_signature_complex",
    "renewal_signature_complex", "resurfacing_signature_complex", "soothing_signature_complex", "brightening_signature_complex",
    "anti_redness_complex", "anti_stress_complex", "anti_pollution_complex", "anti_fatigue_complex",
    "anti_blue_light_complex", "anti_oxidative_stress_complex", "anti_glycation_complex", "anti_inflammation_complex",
    "skin_energy_complex", "skin_repair_complex", "skin_strength_complex", "skin_resilience_complex",
    "skin_elasticity_complex", "skin_firmness_complex", "skin_plumpness_complex", "skin_radiance_complex",
    "skin_smoothness_complex",
    "skin_even_tone_complex", "skin_clarity_complex", "skin_brightness_complex", "skin_glow_complex",
    "skin_hydration_complex", "skin_barrier_complex", "skin_repair_elixir", "skin_firming_elixir",
    "skin_plumping_elixir", "skin_smoothing_elixir", "skin_radiance_elixir", "skin_renewal_elixir",
    "skin_resurfacing_elixir", "skin_brightening_elixir", "skin_soothing_elixir", "skin_balancing_elixir",
    "skin_clarifying_elixir", "skin_strengthening_elixir", "skin_rejuvenation_elixir", "skin_energy_elixir",
    "anti_redness_elixir", "anti_stress_elixir", "anti_pollution_elixir", "anti_fatigue_elixir",
    "anti_blue_light_elixir", "anti_glycation_elixir", "anti_inflammation_elixir", "anti_oxidative_stress_elixir",
    "deep_hydration_matrix", "ultra_hydration_matrix", "barrier_repair_matrix", "lipid_replenish_matrix",
    "moisture_lock_matrix", "water_binding_matrix", "oil_control_matrix", "shine_balance_matrix",
    "pore_refining_matrix", "texture_smoothing_matrix", "tone_balancing_matrix", "brightening_matrix",
    "firming_matrix", "elasticity_matrix", "plumping_matrix", "radiance_matrix",
    "resurfacing_matrix", "renewal_matrix", "clarifying_matrix", "soothing_matrix",
    "marine_collagen_complex", "sea_mineral_complex", "deep_sea_actives", "oceanic_ferment",
    "marine_bioactives", "marine_enzymes", "marine_antioxidants", "marine_brighteners",
    "kelp_ferment", "wakame_ferment", "nori_ferment", "kombu_ferment",
    "spirulina_bioferment", "chlorella_bioferment", "algae_omega_complex", "marine_polysaccharides",
    "thermal_spring_water", "volcanic_spring_water", "glacial_spring_water", "alpine_spring_water",
    "electrolyte_water_complex", "mineral_water_elixir", "hydration_water_elixir", "skin_quenching_water",
    "lotus_flower_extract", "peony_flower_extract", "sakura_flower_extract", "rose_water_extract",
    "hibiscus_extract", "orchid_extract", "jasmine_flower_extract", "ylang_ylang_extract",
    "lavender_flower_extract", "blue_tansy_extract", "violet_extract", "iris_extract",
    "yuzu_extract", "ume_extract", "shiso_extract", "ginger_flower_extract",
    "turmeric_root_ferment", "holy_basil_ferment", "ashwagandha_ferment", "ginseng_root_ferment",
    "mushroom_ferment_complex", "reishi_ferment", "shiitake_ferment", "chaga_ferment",
    "snow_mushroom_ferment", "oat_ferment_complex", "rice_ferment_complex", "soy_ferment_complex",
    "barley_ferment_complex", "wheat_ferment_complex", "probiotic_lysate", "postbiotic_lysate",
    "prebiotic_lysate", "enzyme_lysate", "fruit_enzyme_lysate", "botanical_lysate",
    "vitamin_c_microcapsules", "retinol_microcapsules", "niacinamide_microcapsules", "ceramide_microcapsules",
    "peptide_microcapsules", "antioxidant_microcapsules", "brightening_microcapsules", "hydrating_microcapsules",
    "soothing_microcapsules", "firming_microcapsules", "plumping_microcapsules", "resurfacing_microcapsules",
    "renewal_microcapsules", "clarifying_microcapsules", "balancing_microcapsules", "lipid_microcapsules",
    "nano_hyaluronic_acid", "nano_ceramides", "nano_peptides", "nano_antioxidants",
    "nano_brighteners", "nano_ferments", "nano_lipids", "nano_hydrators",
    "liposomal_delivery_complex", "encapsulated_delivery_complex", "microdelivery_system", "nanodelivery_system",
    "oil_in_water_emulsion", "water_in_oil_emulsion", "gel_emulsion", "serum_emulsion",
    "hydrogel_network", "lipogel_network", "biopolymer_network", "skin_film_network",
    "longwear_film_former", "adhesion_film_former", "flexible_film_former", "breathable_film_former",
    "soft_focus_blur", "hd_blur_powder", "radiance_blur_powder", "matte_blur_powder",
    "silica_airpowder", "mica_airpowder", "boron_nitride_airpowder", "soft_diffusion_powder",
    "skin_smoothing_powder", "skin_radiance_powder", "skin_mattifying_powder", "skin_brightening_powder",
    "sunscreen_filter_blend", "broad_spectrum_filter", "uv_absorber_complex", "uv_scatter_complex",
    "uv_reflective_complex", "blue_light_filter", "infrared_filter", "pollution_shield",
    "anti_adhesion_polymer", "anti_transfer_polymer", "anti_smudge_polymer", "anti_creasing_polymer",
    "makeup_grip_polymer", "skin_grip_polymer", "hydration_grip_polymer", "radiance_grip_polymer",
    "hair_keratin_complex", "hair_bond_complex", "hair_strength_complex", "hair_shine_complex",
    "hair_smoothing_actives", "hair_softening_actives", "hair_hydration_actives", "hair_scalp_actives",
    "scalp_detox_actives", "scalp_balancing_actives", "scalp_soothing_actives", "scalp_renewal_actives",
    "body_aha_blend", "body_bha_blend", "body_urea_blend", "body_shea_blend",
    "body_ceramide_blend", "body_brightening_blend", "body_firming_blend", "body_smoothing_blend",
    "pregnancy_safe_actives", "pregnancy_safe_brighteners", "pregnancy_safe_hydrators", "pregnancy_safe_lipids",
    "pregnancy_safe_antioxidants", "pregnancy_safe_exfoliants", "pregnancy_safe_ferments", "pregnancy_safe_sunscreens",
    "fragrance_free_actives", "hypoallergenic_fragrance_blend", "natural_fragrance_blend", "aroma_therapy_blend",
    "signature_luxury_complex", "signature_radiance_complex", "signature_firming_complex", "signature_hydration_complex",
    "signature_barrier_complex", "signature_glow_complex", "signature_clarity_complex", "signature_renewal_complex",
    "signature_resurfacing_complex", "signature_soothing_complex", "signature_brightening_complex", "signature_energy_complex",
    "anti_redness_actives", "anti_stress_actives", "anti_pollution_actives", "anti_fatigue_actives",
    "anti_blue_light_actives", "anti_glycation_actives", "anti_inflammation_actives", "anti_oxidative_stress_actives",
    "skin_energy_actives", "skin_repair_actives", "skin_strength_actives", "skin_resilience_actives",
    "skin_elasticity_actives", "skin_firmness_actives", "skin_plumpness_actives", "skin_radiance_actives",
    "skin_smoothness_actives", "skin_even_tone_actives", "skin_clarity_actives", "skin_brightness_actives",
    "skin_glow_actives", "skin_hydration_actives", "skin_barrier_actives", "skin_balance_actives",
    "skin_renewal_actives", "skin_resurfacing_actives", "skin_soothing_actives", "skin_brightening_actives",
    "skin_rejuvenation_actives", "skin_repair_booster", "skin_firming_booster", "skin_glow_booster",
    "skin_hydration_booster", "skin_barrier_booster", "skin_clarity_booster", "skin_radiance_booster",
    "skin_smoothing_booster", "skin_plumping_booster", "skin_renewal_booster", "skin_resurfacing_booster",
    "skin_brightening_booster", "skin_soothing_booster", "skin_balancing_booster", "skin_energy_booster",
    "skin_strength_booster", "skin_resilience_booster", "skin_elasticity_booster", "skin_even_tone_booster",
    "skin_brightness_booster", "skin_glow_booster_plus", "skin_firming_booster_plus", "skin_repair_booster_plus",
    "skin_radiance_booster_plus", "skin_smoothing_booster_plus", "skin_plumping_booster_plus", "skin_renewal_booster_plus",
    "skin_resurfacing_booster_plus", "skin_brightening_booster_plus", "skin_soothing_booster_plus", "skin_hydration_booster_plus",
    "skin_barrier_booster_plus", "skin_clarity_booster_plus", "skin_energy_booster_plus", "skin_strength_booster_plus",
    "skin_resilience_booster_plus", "skin_elasticity_booster_plus", "skin_even_tone_booster_plus", "skin_balance_booster_plus",
    "skin_glow_booster_elite", "skin_firming_booster_elite", "skin_repair_booster_elite", "skin_radiance_booster_elite",
    "skin_smoothing_booster_elite", "skin_plumping_booster_elite", "skin_renewal_booster_elite", "skin_resurfacing_booster_elite",
    "skin_brightening_booster_elite", "skin_soothing_booster_elite", "skin_hydration_booster_elite", "skin_barrier_booster_elite",
    "skin_clarity_booster_elite", "skin_energy_booster_elite", "skin_strength_booster_elite", "skin_resilience_booster_elite",
    "skin_elasticity_booster_elite", "skin_even_tone_booster_elite", "skin_balance_booster_elite", "skin_glow_actives_elite", 
    "ultra_hydrating_actives", "deep_repair_actives", "intense_firming_actives", "advanced_brightening_actives",
    "clinical_grade_peptides", "clinical_grade_antioxidants", "clinical_grade_brighteners", "clinical_grade_hydrators",
    "clinical_grade_lipids", "clinical_grade_ferments", "clinical_grade_exfoliants", "clinical_grade_sunscreens",
    "luxury_skin_elixirs", "luxury_bioactives", "luxury_ferment_complex", "luxury_peptide_complex",
    "luxury_antioxidant_complex", "luxury_brightening_complex", "luxury_hydration_complex", "luxury_barrier_complex",
    "luxury_radiance_complex", "luxury_resurfacing_complex", "luxury_renewal_complex", "luxury_soothing_complex",
    "luxury_firming_complex", "luxury_plumping_complex", "luxury_even_tone_complex", "luxury_clarity_complex",
    "luxury_energy_complex", "luxury_strength_complex", "luxury_resilience_complex", "luxury_elasticity_complex",
    "bioactive_peptide_blend", "bioactive_ferment_blend", "bioactive_antioxidant_blend", "bioactive_brightening_blend",
    "bioactive_hydration_blend", "bioactive_barrier_blend", "bioactive_radiance_blend", "bioactive_resurfacing_blend",
    "bioactive_renewal_blend", "bioactive_soothing_blend", "bioactive_firming_blend", "bioactive_plumping_blend",
    "bioactive_even_tone_blend", "bioactive_clarity_blend", "bioactive_energy_blend", "bioactive_strength_blend",
    "bioactive_resilience_blend", "bioactive_elasticity_blend", "advanced_skin_repair", "advanced_skin_firming",
    "advanced_skin_brightening", "advanced_skin_hydration", "advanced_skin_barrier", "advanced_skin_radiance",
    "advanced_skin_resurfacing", "advanced_skin_renewal", "advanced_skin_soothing", "advanced_skin_clarity",
    "advanced_skin_even_tone", "advanced_skin_elasticity", "advanced_skin_plumping", "advanced_skin_smoothing",
    "advanced_skin_energy", "advanced_skin_strength", "advanced_skin_resilience", "advanced_skin_balance",
    "ultra_firming_actives", "ultra_brightening_actives", "ultra_resurfacing_actives", "ultra_renewal_actives",
    "ultra_soothing_actives", "ultra_clarity_actives", "ultra_even_tone_actives", "ultra_elasticity_actives",
    "ultra_plumping_actives", "ultra_smoothing_actives", "ultra_radiance_actives", "ultra_barrier_actives",
    "ultra_hydration_actives", "ultra_energy_actives", "ultra_strength_actives", "ultra_resilience_actives",
    "pro_firming_actives", "pro_brightening_actives", "pro_resurfacing_actives", "pro_renewal_actives",
    "pro_soothing_actives", "pro_clarity_actives", "pro_even_tone_actives", "pro_elasticity_actives",
    "pro_plumping_actives", "pro_smoothing_actives", "pro_radiance_actives", "pro_barrier_actives",
    "pro_hydration_actives", "pro_energy_actives", "pro_strength_actives", "pro_resilience_actives",
    "elite_firming_actives", "elite_brightening_actives", "elite_resurfacing_actives", "elite_renewal_actives",
    "elite_soothing_actives", "elite_clarity_actives", "elite_even_tone_actives", "elite_elasticity_actives",
    "elite_plumping_actives", "elite_smoothing_actives", "elite_radiance_actives", "elite_barrier_actives",
    "elite_hydration_actives", "elite_energy_actives", "elite_strength_actives", "elite_resilience_actives",
    "clinical_firming_actives", "clinical_brightening_actives", "clinical_resurfacing_actives", "clinical_renewal_actives",
    "clinical_soothing_actives", "clinical_clarity_actives", "clinical_even_tone_actives", "clinical_elasticity_actives",
    "clinical_plumping_actives", "clinical_smoothing_actives", "clinical_radiance_actives", "clinical_barrier_actives",
    "clinical_hydration_actives", "clinical_energy_actives", "clinical_strength_actives", "clinical_resilience_actives",
    "peptide_repair_elite", "peptide_firming_elite", "peptide_brightening_elite", "peptide_hydration_elite",
    "peptide_barrier_elite", "peptide_radiance_elite", "peptide_resurfacing_elite", "peptide_renewal_elite",
    "peptide_soothing_elite", "peptide_clarity_elite", "peptide_even_tone_elite", "peptide_elasticity_elite",
    "peptide_plumping_elite", "peptide_smoothing_elite", "peptide_energy_elite", "peptide_strength_elite",
    "peptide_resilience_elite", "lipid_repair_elite", "lipid_barrier_elite", "lipid_hydration_elite",
    "lipid_radiance_elite", "lipid_brightening_elite", "lipid_resurfacing_elite", "lipid_renewal_elite",
    "lipid_soothing_elite", "lipid_clarity_elite", "lipid_even_tone_elite", "lipid_elasticity_elite",
    "lipid_plumping_elite", "lipid_smoothing_elite", "lipid_energy_elite", "lipid_strength_elite",
    "lipid_resilience_elite", "ferment_repair_elite", "ferment_brightening_elite", "ferment_hydration_elite",
    "ferment_barrier_elite", "ferment_radiance_elite", "ferment_resurfacing_elite", "ferment_renewal_elite",
    "ferment_soothing_elite", "ferment_clarity_elite", "ferment_even_tone_elite", "ferment_elasticity_elite",
    "ferment_plumping_elite", "ferment_smoothing_elite", "ferment_energy_elite", "ferment_strength_elite",
    "ferment_resilience_elite", "antioxidant_repair_elite", "antioxidant_brightening_elite", "antioxidant_hydration_elite",
    "antioxidant_barrier_elite", "antioxidant_radiance_elite", "antioxidant_resurfacing_elite", "antioxidant_renewal_elite",
    "antioxidant_soothing_elite", "antioxidant_clarity_elite", "antioxidant_even_tone_elite", "antioxidant_elasticity_elite",
    "antioxidant_plumping_elite", "antioxidant_smoothing_elite", "antioxidant_energy_elite", "antioxidant_strength_elite",
    "antioxidant_resilience_elite", "brightening_repair_elite", "brightening_firming_elite", "brightening_hydration_elite",
    "brightening_barrier_elite", "brightening_radiance_elite", "brightening_resurfacing_elite", 
    "brightening_barrier_elite", "brightening_radiance_elite", "brightening_resurfacing_elite", "brightening_renewal_elite",
    "brightening_soothing_elite", "brightening_clarity_elite", "brightening_even_tone_elite", "brightening_elasticity_elite",
    "brightening_plumping_elite", "brightening_smoothing_elite", "brightening_energy_elite", "brightening_strength_elite",
    "brightening_resilience_elite", "hydration_repair_elite", "hydration_firming_elite", "hydration_brightening_elite",
    "hydration_barrier_elite", "hydration_radiance_elite", "hydration_resurfacing_elite", "hydration_renewal_elite",
    "hydration_soothing_elite", "hydration_clarity_elite", "hydration_even_tone_elite", "hydration_elasticity_elite",
    "hydration_plumping_elite", "hydration_smoothing_elite", "hydration_energy_elite", "hydration_strength_elite",
    "hydration_resilience_elite", "barrier_repair_elite_plus", "barrier_strength_elite_plus", "barrier_resilience_elite_plus",
    "barrier_hydration_elite_plus", "barrier_firming_elite_plus", "barrier_brightening_elite_plus", "barrier_radiance_elite_plus",
    "barrier_smoothing_elite_plus", "barrier_even_tone_elite_plus", "barrier_clarity_elite_plus", "barrier_energy_elite_plus",
    "barrier_elasticity_elite_plus", "barrier_plumping_elite_plus", "barrier_renewal_elite_plus", "barrier_resurfacing_elite_plus",
    "radiance_repair_elite", "radiance_firming_elite", "radiance_brightening_elite", "radiance_hydration_elite",
    "radiance_barrier_elite", "radiance_resurfacing_elite", "radiance_renewal_elite", "radiance_soothing_elite",
    "radiance_clarity_elite", "radiance_even_tone_elite", "radiance_elasticity_elite", "radiance_plumping_elite",
    "radiance_smoothing_elite", "radiance_energy_elite", "radiance_strength_elite", "radiance_resilience_elite",
    "resurfacing_repair_elite", "resurfacing_firming_elite", "resurfacing_brightening_elite", "resurfacing_hydration_elite",
    "resurfacing_barrier_elite", "resurfacing_radiance_elite", "resurfacing_renewal_elite", "resurfacing_soothing_elite",
    "resurfacing_clarity_elite", "resurfacing_even_tone_elite", "resurfacing_elasticity_elite", "resurfacing_plumping_elite",
    "resurfacing_smoothing_elite", "resurfacing_energy_elite", "resurfacing_strength_elite", "resurfacing_resilience_elite",
    "renewal_repair_elite", "renewal_firming_elite", "renewal_brightening_elite", "renewal_hydration_elite",
    "renewal_barrier_elite", "renewal_radiance_elite", "renewal_resurfacing_elite", "renewal_soothing_elite",
    "renewal_clarity_elite", "renewal_even_tone_elite", "renewal_elasticity_elite", "renewal_plumping_elite",
    "renewal_smoothing_elite", "renewal_energy_elite", "renewal_strength_elite", "renewal_resilience_elite",
    "soothing_repair_elite", "soothing_firming_elite", "soothing_brightening_elite", "soothing_hydration_elite",
    "soothing_barrier_elite", "soothing_radiance_elite", "soothing_resurfacing_elite", "soothing_renewal_elite",
    "soothing_clarity_elite", "soothing_even_tone_elite", "soothing_elasticity_elite", "soothing_plumping_elite",
    "soothing_smoothing_elite", "soothing_energy_elite", "soothing_strength_elite", "soothing_resilience_elite",
    "clarity_repair_elite", "clarity_firming_elite", "clarity_brightening_elite", "clarity_hydration_elite",
    "clarity_barrier_elite", "clarity_radiance_elite", "clarity_resurfacing_elite", "clarity_renewal_elite",
    "clarity_soothing_elite", "clarity_even_tone_elite", "clarity_elasticity_elite", "clarity_plumping_elite",
    "clarity_smoothing_elite", "clarity_energy_elite", "clarity_strength_elite", "clarity_resilience_elite",
    "even_tone_repair_elite", "even_tone_firming_elite", "even_tone_brightening_elite", "even_tone_hydration_elite",
    "even_tone_barrier_elite", "even_tone_radiance_elite", "even_tone_resurfacing_elite", "even_tone_renewal_elite",
    "even_tone_soothing_elite", "even_tone_clarity_elite", "even_tone_elasticity_elite", "even_tone_plumping_elite",
    "even_tone_smoothing_elite", "even_tone_energy_elite", "even_tone_strength_elite", "even_tone_resilience_elite",
    "elasticity_repair_elite", "elasticity_firming_elite", "elasticity_brightening_elite", "elasticity_hydration_elite",
    "elasticity_barrier_elite", "elasticity_radiance_elite", "elasticity_resurfacing_elite", "elasticity_renewal_elite",
    "elasticity_soothing_elite", "elasticity_clarity_elite", "elasticity_even_tone_elite", "elasticity_plumping_elite",
    "elasticity_smoothing_elite", "elasticity_energy_elite", "elasticity_strength_elite", "elasticity_resilience_elite",
    "plumping_repair_elite", "plumping_firming_elite", "plumping_brightening_elite", "plumping_hydration_elite",
    "plumping_barrier_elite", "plumping_radiance_elite", "plumping_resurfacing_elite", "plumping_renewal_elite",
    "plumping_soothing_elite", "plumping_clarity_elite", "plumping_even_tone_elite", "plumping_elasticity_elite",
    "plumping_smoothing_elite", "plumping_energy_elite", "plumping_strength_elite", "plumping_resilience_elite",
    "smoothing_repair_elite", "smoothing_firming_elite", "smoothing_brightening_elite", "smoothing_hydration_elite",
    "smoothing_barrier_elite", "smoothing_radiance_elite", "smoothing_resurfacing_elite", "smoothing_renewal_elite",
    "smoothing_soothing_elite", "smoothing_clarity_elite", "smoothing_even_tone_elite", "smoothing_elasticity_elite",
    "smoothing_plumping_elite", "smoothing_energy_elite", "smoothing_strength_elite", "smoothing_resilience_elite",
    "energy_repair_elite", "energy_firming_elite", "energy_brightening_elite", "energy_hydration_elite",
    "energy_barrier_elite", "energy_radiance_elite", "energy_resurfacing_elite", "energy_renewal_elite",
    "energy_soothing_elite", "energy_clarity_elite", "energy_even_tone_elite", "energy_elasticity_elite",
    "energy_plumping_elite", "energy_smoothing_elite", "energy_strength_elite", "energy_resilience_elite",
    "strength_repair_elite", "strength_firming_elite", "strength_brightening_elite", "strength_hydration_elite",
    "strength_barrier_elite", "strength_radiance_elite", "strength_resurfacing_elite", "strength_renewal_elite",
    "strength_soothing_elite", "strength_clarity_elite", "strength_even_tone_elite", "strength_elasticity_elite",
    "strength_plumping_elite", "strength_smoothing_elite", "strength_energy_elite", "strength_resilience_elite",
    "resilience_repair_elite", "resilience_firming_elite", "resilience_brightening_elite", "resilience_hydration_elite",
    "resilience_barrier_elite", "resilience_radiance_elite", "resilience_resurfacing_elite", "resilience_renewal_elite",
    "resilience_soothing_elite", "resilience_clarity_elite", "resilience_even_tone_elite", "resilience_elasticity_elite",
    "resilience_plumping_elite", "resilience_smoothing_elite", "resilience_energy_elite", "resilience_strength_elite",
    "resilience_elite_plus", "radiance_elite_plus", "clarity_elite_plus", "hydration_elite_plus",
    "barrier_elite_plus", "firming_elite_plus", "brightening_elite_plus", "renewal_elite_plus",
    "resurfacing_elite_plus", "soothing_elite_plus", "even_tone_elite_plus", "elasticity_elite_plus",
    "plumping_elite_plus", "smoothing_elite_plus", "energy_elite_plus", "strength_elite_plus",
    "ultra_repair_complex", "ultra_firming_complex", "ultra_brightening_complex", "ultra_hydration_complex",
    "ultra_barrier_complex", "ultra_radiance_complex", "ultra_resurfacing_complex", "ultra_renewal_complex",
    "ultra_soothing_complex", "ultra_clarity_complex", "ultra_even_tone_complex", "ultra_elasticity_complex",
    "ultra_plumping_complex", "ultra_smoothing_complex", "ultra_energy_complex", "ultra_strength_complex",
    "ultra_resilience_complex", "supreme_repair_complex", "supreme_firming_complex", "supreme_brightening_complex",
    "supreme_hydration_complex", "supreme_barrier_complex", "supreme_radiance_complex", "supreme_resurfacing_complex",
    "supreme_renewal_complex", "supreme_soothing_complex", "supreme_clarity_complex", "supreme_even_tone_complex",
    "supreme_elasticity_complex", "supreme_plumping_complex", "supreme_smoothing_complex", "supreme_energy_complex",
    "supreme_strength_complex", "supreme_resilience_complex", "prestige_repair_complex", "prestige_firming_complex",
    "prestige_brightening_complex", "prestige_hydration_complex", "prestige_barrier_complex", "prestige_radiance_complex",
    "prestige_resurfacing_complex", "prestige_renewal_complex", "prestige_soothing_complex", "prestige_clarity_complex",
    "prestige_even_tone_complex", "prestige_elasticity_complex", "prestige_plumping_complex", "prestige_smoothing_complex",
    "prestige_energy_complex", "prestige_strength_complex", "prestige_resilience_complex"
]

__all__ = [
    "SKIN_TYPES", 
    "SKINCARE_TEXTURES",
    "SKINCARE_BENEFITS",
    "SKINCARE_ACTIVES",
    "SKIN_GOALS",
    "SKIN_CONCERNS",
    "SKIN_INGREDIENTS"
]