# CORE VOCAB BANKS FOR MVQUEEN OMNILUXE ENGINE

# -----------------------------------------
# PERSONA CONFIGURATION
# -----------------------------------------
PERSONA_CONFIG = {
    "MVQueen Core": {
        "tone": "luxury-confident-soft-feminine",
        "emotional_axes": ["radiance", "self-belief", "soft power"],
        "seo_bias": ["luxury skincare", "modern beauty", "elevated essentials"],
        "cta_style": "soft imperative",
    },

    "MISS.QUEEN": {
        "tone": "playful-glam-feminine",
        "emotional_axes": ["fun", "glow", "self-expression"],
        "seo_bias": ["soft glam", "night-out looks"],
        "cta_style": "playful invitation",
    },

    "Victoria Soft Power": {
        "tone": "sensual-soft-power",
        "emotional_axes": ["allure", "confidence", "intimacy"],
        "seo_bias": ["lingerie-inspired beauty", "soft power dressing"],
        "cta_style": "whispered persuasion",
    },

    "Sephora Precision": {
        "tone": "clinical-precise-modern",
        "emotional_axes": ["results", "clarity", "control"],
        "seo_bias": ["clinical skincare", "active ingredients"],
        "cta_style": "clear directive",
    },

    "Runway Modern": {
        "tone": "editorial-bold-runway",
        "emotional_axes": ["impact", "presence", "statement"],
        "seo_bias": ["runway looks", "editorial fashion"],
        "cta_style": "commanding",
    },

    "Clinical Chic": {
        "tone": "minimal-clinical-luxe",
        "emotional_axes": ["purity", "refinement", "assurance"],
        "seo_bias": ["dermatologist-inspired", "clean formulas"],
        "cta_style": "assured guidance",
    },

    "Soft Luxury": {
        "tone": "whisper-soft-luxury",
        "emotional_axes": ["comfort", "ease", "quiet confidence"],
        "seo_bias": ["everyday luxury", "soft textures"],
        "cta_style": "gentle suggestion",
    },

    "Glow Maestro": {
        "tone": "radiant-glow-obsessed",
        "emotional_axes": ["luminosity", "energy", "vitality"],
        "seo_bias": ["glowing skin", "radiant finish"],
        "cta_style": "hype but refined",
    },

    "Elegant Authority": {
        "tone": "refined-commanding-luxe",
        "emotional_axes": ["leadership", "presence", "composure"],
        "seo_bias": ["power dressing", "boardroom beauty"],
        "cta_style": "decisive invitation",
    },

    "Street Luxe Femme": {
        "tone": "street-modern-luxe",
        "emotional_axes": ["edge", "self-definition", "movement"],
        "seo_bias": ["street style", "city-ready looks"],
        "cta_style": "cool directive",
    },
}

ADJECTIVES = [
    "opulent", "radiant", "sleek", "polished", "refined", "velvety", "silken",
    "glossy", "luminous", "sumptuous", "elegant", "pristine", "crisp", "buttery",
    "weightless", "featherlight", "satin-soft", "cashmere-smooth", "gilded",
    "sculpted", "tailored", "structured", "minimalist", "maximalist", "timeless",
    "modernist", "artful", "sophisticated", "elevated", "premium", "ultra-soft",
    "ultra-fine", "ultra-smooth", "ultra-rich", "silky-matte", "glazed",
    "pearlescent", "iridescent", "translucent", "diffused", "blurred", "soft-focus",
    "high-impact", "high-definition", "high-shine", "high-luxe", "high-polish",
    "high-clarity", "high-precision", "high-performance", "high-intent",
    "high-fashion", "couture-level", "runway-ready", "editorial-grade",
    "studio-perfect", "camera-ready", "photo-finish", "airbrushed", "seamless",
    "effortless", "fluid", "melted", "molten", "velour-like", "cashmere-like",
    "featherlike", "cloudlike", "pillowy", "cushioned", "plush", "rich",
    "deep", "intense", "vibrant", "soft", "muted", "neutral", "warm-toned",
    "cool-toned", "balanced", "harmonized", "layered", "dimensional",
    "multi-dimensional", "sculptural", "architectural", "precise", "clean",
    "crisp-edged", "blur-softened", "diffusion-rich", "glow-forward",
    "radiance-boosting", "light-catching", "light-reflective", "light-diffusing",
    "light-enhancing", "skin-like", "second-skin", "barely-there", "naturalistic",
    "hyper-natural", "hyper-real", "ultra-real", "true-to-skin", "true-to-tone",
    "true-to-color", "color-true", "color-rich", "pigment-dense", "pigment-soft",
    "pigment-balanced", "pigment-sheer", "pigment-buildable", "buildable",
    "blendable", "stretchable", "flexible", "adaptive", "intelligent",
    "smart-textured", "smart-finish", "smart-blend", "smart-wear", "long-wear",
    "extended-wear", "all-day", "all-night", "transfer-resistant",
    "humidity-resistant", "sweat-resistant", "crease-resistant", "fade-resistant",
    "life-proof", "weather-proof", "studio-proof", "runway-proof", "event-ready",
    "occasion-ready", "luxury-grade", "boutique-level", "signature-level",
    "heritage-inspired", "modern-classic", "future-forward", "trend-forward",
    "fashion-forward", "style-driven", "vibe-driven", "persona-driven",
    "identity-rich", "statement-making", "quiet-luxe", "bold-luxe",
    "soft-luxe", "clean-luxe", "street-luxe", "editorial-luxe",
    "couture-luxe", "runway-luxe", "resort-luxe", "evening-luxe",
    "day-to-night", "versatile", "multi-use", "multi-functional",
    "performance-driven", "results-driven", "ritual-ready", "routine-ready",
    "skin-enhancing", "tone-enhancing", "texture-enhancing", "finish-enhancing",
    "glow-enhancing", "clarity-enhancing", "smoothness-enhancing",
    "softness-enhancing", "hydration-rich", "moisture-rich", "nourishing",
    "conditioning", "revitalizing", "rejuvenating", "energizing", "balancing",
    "calming", "soothing", "cooling", "warming", "comforting", "uplifting",
    "empowering", "confidence-boosting", "presence-enhancing", "impactful",
    "memorable", "signature", "iconic", "distinctive", "recognizable",
    "collectible", "limited-edition", "exclusive", "premium-crafted",
    "artisan-crafted", "precision-crafted", "studio-crafted", "couture-crafted",
    "hand-finished", "hand-detailed", "hand-polished", "hand-refined",
    "expertly-blended", "expertly-finished", "expertly-sculpted",
    "expertly-designed", "expertly-formulated", "expertly-curated"
    "curated", "edited", "refined", "perfected", "optimized", "enhanced",
    "elevated", "heightened", "amplified", "intensified", "softened",
    "smoothed", "polished", "refreshed", "renewed", "revived", "reimagined",
    "redefined", "reinvented", "reinterpreted", "modernized", "evolved",
    "transformed", "elevated", "luxurious", "premium", "high-end",
    "boutique", "designer", "couture", "runway", "editorial", "artistic",
    "creative", "visionary", "inspired", "inspirational", "aspirational",
    "dreamlike", "ethereal", "angelic", "heavenly", "celestial", "glowing",
    "shimmering", "sparkling", "radiating", "gleaming", "glinting",
    "glittering", "glossed", "lacquered", "polished", "buffed", "refined",
    "smooth", "silky", "velvety", "buttery", "creamy", "mousse-like",
    "whipped", "airy", "cloud-soft", "pillowy", "cushioned", "bouncy",
    "elastic", "stretchy", "flexible", "adaptive", "intelligent",
    "smart-wear", "smart-finish", "smart-texture", "smart-blend",
    "smart-performance", "smart-coverage", "smart-color", "smart-tone",
    "smart-glow", "smart-radiance", "smart-diffusion", "smart-clarity",
    "smart-sculpt", "smart-define", "smart-lift", "smart-smooth",
    "smart-hydrate", "smart-nourish", "smart-energize", "smart-refresh",
    "smart-revive", "smart-restore", "smart-enhance", "smart-elevate",
    "smart-perfect", "smart-optimize", "smart-refine", "smart-soften",
    "smart-intensify", "smart-amplify", "smart-boost", "smart-balance",
    "smart-calm", "smart-soothe", "smart-comfort", "smart-protect",
    "smart-shield", "smart-guard", "smart-preserve"
    "ultra-luxe", "hyper-luxe", "deep-luxe", "soft-touch", "feather-touch",
    "precision-soft", "precision-smooth", "precision-rich", "precision-refined",
    "precision-polished", "precision-balanced", "precision-layered",
    "precision-crafted", "precision-finished", "precision-detailed",
    "precision-edged", "precision-shaped", "precision-toned",
    "precision-glow", "precision-radiance", "precision-diffusion",
    "precision-clarity", "precision-focus", "precision-definition",
    "precision-sculpt", "precision-lift", "precision-structure",
    "precision-architecture", "precision-design", "precision-form",
    "precision-texture", "precision-finish", "precision-color",
    "precision-tone", "precision-depth", "precision-intensity",
    "precision-softness", "precision-smoothness", "precision-hydration",
    "precision-nourishment", "precision-energy", "precision-balance",
    "precision-calm", "precision-soothe", "precision-comfort",
    "precision-protect", "precision-shield", "precision-guard",
    "precision-preserve", "precision-enhance", "precision-elevate",
    "precision-perfect", "precision-optimize", "precision-refine",
    "precision-soften", "precision-intensify", "precision-amplify",
    "precision-boost", "precision-restore", "precision-revive",
    "precision-refresh", "precision-renew", "precision-redefine",
    "precision-reimagine", "precision-evolve", "precision-transform",
    "precision-modernize", "precision-advance", "precision-progressive",
    "precision-futuristic", "precision-forward", "precision-elite",
    "precision-premium", "precision-signature", "precision-iconic",
    "precision-distinctive", "precision-collectible", "precision-exclusive",
    "precision-limited", "precision-curated", "precision-edited",
    "precision-artisan", "precision-handcrafted", "precision-handfinished",
    "precision-handpolished", "precision-handrefined", "precision-expert",
    "precision-mastered", "precision-engineered", "precision-developed",
    "precision-formulated", "precision-blended", "precision-sculpted",
    "precision-styled", "precision-tailored", "precision-structured",
    "precision-layered", "precision-dimensional", "precision-multidimensional",
    "precision-balanced", "precision-harmonized", "precision-synchronized",
    "precision-integrated", "precision-unified", "precision-cohesive",
    "precision-seamless", "precision-fluid", "precision-effortless",
    "precision-weightless", "precision-airy", "precision-cloudlike",
    "precision-cushioned", "precision-pillowy", "precision-bouncy",
    "precision-elastic", "precision-flexible", "precision-adaptive",
    "precision-intelligent", "precision-smart", "precision-responsive",
    "precision-dynamic", "precision-evolving", "precision-living",
    "precision-breathable", "precision-softwear", "precision-skinwear",
    "precision-bodywear", "precision-fashionwear", "precision-luxewear",
    "precision-performancewear", "precision-studiowear", "precision-runwaywear",
    "precision-editorialwear", "precision-eventwear", "precision-eveningwear",
    "precision-daywear", "precision-nightwear", "precision-resortwear",
    "precision-holidaywear", "precision-seasonal", "precision-transitional",
    "precision-versatile", "precision-multiuse", "precision-multifunctional",
    "precision-transformative", "precision-elevating", "precision-enhancing",
    "precision-boosting", "precision-clarifying", "precision-smoothing",
    "precision-softening", "precision-hydrating", "precision-nourishing",
    "precision-revitalizing", "precision-rejuvenating", "precision-energizing",
    "precision-balancing", "precision-calming", "precision-soothing",
    "precision-cooling", "precision-warming", "precision-comforting",
    "precision-uplifting", "precision-empowering", "precision-impactful",
    "precision-memorable", "precision-signature", "precision-iconic",
    "precision-distinct", "precision-recognizable", "precision-collectible",
    "precision-exclusive", "precision-premium", "precision-luxe"
    "ultra-premium", "ultra-refined", "ultra-elevated", "ultra-polished",
    "ultra-sculpted", "ultra-defined", "ultra-clarified", "ultra-balanced",
    "ultra-harmonized", "ultra-synchronized", "ultra-integrated",
    "ultra-unified", "ultra-cohesive", "ultra-seamless", "ultra-fluid",
    "ultra-effortless", "ultra-weightless", "ultra-airy", "ultra-cloudlike",
    "ultra-cushioned", "ultra-pillowy", "ultra-bouncy", "ultra-elastic",
    "ultra-flexible", "ultra-adaptive", "ultra-intelligent", "ultra-smart",
    "ultra-responsive", "ultra-dynamic", "ultra-evolving", "ultra-living",
    "ultra-breathable", "ultra-softwear", "ultra-skinwear", "ultra-bodywear",
    "ultra-fashionwear", "ultra-luxewear", "ultra-performancewear",
    "ultra-studiowear", "ultra-runwaywear", "ultra-editorialwear",
    "ultra-eventwear", "ultra-eveningwear", "ultra-daywear", "ultra-nightwear",
    "ultra-resortwear", "ultra-holidaywear", "ultra-seasonal",
    "ultra-transitional", "ultra-versatile", "ultra-multiuse",
    "ultra-multifunctional", "ultra-transformative", "ultra-elevating",
    "ultra-enhancing", "ultra-boosting", "ultra-clarifying", "ultra-smoothing",
    "ultra-softening", "ultra-hydrating", "ultra-nourishing",
    "ultra-revitalizing", "ultra-rejuvenating", "ultra-energizing",
    "ultra-balancing", "ultra-calming", "ultra-soothing", "ultra-cooling",
    "ultra-warming", "ultra-comforting", "ultra-uplifting", "ultra-empowering",
    "ultra-impactful", "ultra-memorable", "ultra-signature", "ultra-iconic",
    "ultra-distinct", "ultra-recognizable", "ultra-collectible",
    "ultra-exclusive", "ultra-designer", "ultra-couture", "ultra-runway",
    "ultra-editorial", "ultra-artistic", "ultra-creative", "ultra-visionary",
    "ultra-inspired", "ultra-aspirational", "ultra-dreamlike", "ultra-ethereal",
    "ultra-angelic", "ultra-heavenly", "ultra-celestial", "ultra-glowing",
    "ultra-shimmering", "ultra-sparkling", "ultra-radiating", "ultra-gleaming",
    "ultra-glinting", "ultra-glittering", "ultra-glossed", "ultra-lacquered",
    "ultra-buffed", "ultra-polished", "ultra-refined", "ultra-smooth",
    "ultra-silky", "ultra-velvety", "ultra-buttery", "ultra-creamy",
    "ultra-whipped", "ultra-airbrushed", "ultra-photo", "ultra-studio",
    "ultra-camera", "ultra-hd", "ultra-ultrahd", "ultra-4k", "ultra-8k",
    "ultra-hyperreal", "ultra-natural", "ultra-hypernatural",
    "ultra-skinlike", "ultra-secondskin", "ultra-truecolor",
    "ultra-trueglow", "ultra-truefinish", "ultra-trueclarity",
    "ultra-trueintensity", "ultra-truebalance", "ultra-trueharmony",
    "ultra-trueprecision", "ultra-trueperformance", "ultra-trueelevation",
    "ultra-trueenhancement", "ultra-trueperfection", "ultra-trueoptimization",
    "ultra-truerefine", "ultra-truesoften", "ultra-trueintensify",
    "ultra-trueamplify", "ultra-trueboost", "ultra-truerestore",
    "ultra-truerenew", "ultra-truerefresh", "ultra-truerevive",
    "ultra-truereimagine", "ultra-trueredefine", "ultra-trueevolve",
    "ultra-truetransform", "ultra-trueadvance", "ultra-trueprogressive",
    "ultra-truefuture", "ultra-trueelite", "ultra-truepremium",
    "hyper-premium", "hyper-refined", "hyper-elevated", "hyper-polished",
    "hyper-sculpted", "hyper-defined", "hyper-clarified", "hyper-balanced",
    "hyper-harmonized", "hyper-synchronized", "hyper-integrated",
    "hyper-unified", "hyper-cohesive", "hyper-seamless", "hyper-fluid",
    "hyper-effortless", "hyper-weightless", "hyper-airy", "hyper-cloudlike",
    "hyper-cushioned", "hyper-pillowy", "hyper-bouncy", "hyper-elastic",
    "hyper-flexible", "hyper-adaptive", "hyper-intelligent", "hyper-smart",
    "hyper-responsive", "hyper-dynamic", "hyper-evolving", "hyper-living",
    "hyper-breathable", "hyper-softwear", "hyper-skinwear", "hyper-bodywear",
    "hyper-fashionwear", "hyper-luxewear", "hyper-performancewear",
    "hyper-studiowear", "hyper-runwaywear", "hyper-editorialwear",
    "hyper-eventwear", "hyper-eveningwear", "hyper-daywear", "hyper-nightwear",
    "hyper-resortwear", "hyper-holidaywear", "hyper-seasonal",
    "hyper-transitional", "hyper-versatile", "hyper-multiuse",
    "hyper-multifunctional", "hyper-transformative", "hyper-elevating",
    "hyper-enhancing", "hyper-boosting", "hyper-clarifying", "hyper-smoothing",
    "hyper-softening", "hyper-hydrating", "hyper-nourishing",
    "hyper-revitalizing", "hyper-rejuvenating", "hyper-energizing",
    "hyper-balancing", "hyper-calming", "hyper-soothing", "hyper-cooling",
    "hyper-warming", "hyper-comforting", "hyper-uplifting", "hyper-empowering",
    "hyper-impactful", "hyper-memorable", "hyper-signature", "hyper-iconic",
    "hyper-distinct", "hyper-recognizable", "hyper-collectible",
    "hyper-exclusive", "hyper-designer", "hyper-couture", "hyper-runway",
    "hyper-editorial", "hyper-artistic", "hyper-creative", "hyper-visionary",
    "hyper-inspired", "hyper-aspirational", "hyper-dreamlike", "hyper-ethereal",
    "hyper-angelic", "hyper-heavenly", "hyper-celestial", "hyper-glowing",
    "hyper-shimmering", "hyper-sparkling", "hyper-radiating", "hyper-gleaming",
    "hyper-glinting", "hyper-glittering", "hyper-glossed", "hyper-lacquered",
    "hyper-buffed", "hyper-polished", "hyper-refined", "hyper-smooth",
    "hyper-silky", "hyper-velvety", "hyper-buttery", "hyper-creamy",
    "hyper-whipped", "hyper-airbrushed", "hyper-photo", "hyper-studio",
    "hyper-camera", "hyper-hd", "hyper-ultrahd", "hyper-4k", "hyper-8k",
    "hyper-hyperreal", "hyper-natural", "hyper-hypernatural",
    "hyper-skinlike", "hyper-secondskin", "hyper-truecolor",
    "hyper-trueglow", "hyper-truefinish", "hyper-trueclarity",
    "hyper-trueintensity", "hyper-truebalance", "hyper-trueharmony",
    "hyper-trueprecision", "hyper-trueperformance", "hyper-trueelevation",
    "hyper-trueenhancement", "hyper-trueperfection", "hyper-trueoptimization",
    "hyper-truerefine", "hyper-truesoften", "hyper-trueintensify",
    "hyper-trueamplify", "hyper-trueboost", "hyper-truerestore",
    "hyper-truerenew", "hyper-truerefresh", "hyper-truerevive",
    "hyper-truereimagine", "hyper-trueredefine", "hyper-trueevolve",
    "hyper-truetransform", "hyper-trueadvance", "hyper-trueprogressive",
    "hyper-truefuture", "hyper-trueelite", "hyper-truepremium",
    "hyper-truesignature"
]

PERSONAS = [
    "Soft Luxury", "Runway Modern", "Clinical Chic", "Street Luxe Femme", "MISS.QUEEN", "Glow Maestro",
    "Elegant Authority", "Content Creator Core", "Old Money Modern", "MVQueen Core"
]

MOODS = [
    "Soft Glam", "Clean Girl", "Luxury Glow", "Bold Beauty", "Minimal Chic",
    "Romantic", "Confident", "Effortless", "Polished", "Fresh Face", "Sultry",
    "Runway", "Editorial", "Natural Beauty", "High Glam", "Subtle Glam",
    "Power Look", "Soft Power", "Feminine", "Modern Muse", "Chic Minimal",
    "Golden Hour", "Bare Glow", "Statement Look", "Date Night", "CEO Energy",
    "Girl Boss", "Cool Girl", "City Glow", "Vacation Mode", "Parisian",
    "New York Glam", "LA Glow", "Beachy", "Bronzed", "Crystal Glow",
    "Velvet Nights", "Dream Skin", "Glow Queen", "MVQueen Energy",
    "Signature Glow", "Elevated Beauty", "Quiet Luxury", "High Shine",
    "Glow Mood", "Glossy Energy", "Soft Radiance", "Refined", "Delicate",
    "Bold Radiance", "Glow Era", "Velvet Era", "Skin Era", "Confidence Boost",
    "Flirty", "Graceful", "Glow Ritual", "Luxury Ritual", "Signature Routine",
    "Iconic Glow", "Daily Glam", "Glow Edit", "Radiant Mood", "Luxe Skin",
    "Timeless", "Youthful", "Ageless Glow", "Classic Beauty", "Modern Glow",
    "Elite Finish", "VIP Energy"
]

OCCASIONS = [
    "Everyday Wear", "Date Night", "Event Ready", "Bridal Glow", "Vacation Beauty",
    "Work Ready", "Weekend Glow", "Photoshoot Ready", "Red Carpet", "Birthday Glam",
    "Anniversary", "Holiday Glam", "Summer Glow", "Winter Care", "Spring Refresh",
    "Fall Glow", "Travel Friendly", "On-The-Go", "Office Chic", "Dinner Ready",
    "Party Ready", "Festival", "Night Out", "Gym Bag", "Beach Day", "Poolside",
    "Airport Look", "Business Meeting", "Formal Event", "Casual Day", "Brunch Ready",
    "Quick Glam", "After Work", "Wedding Guest", "Baby Shower", "Graduation",
    "Prom", "Luxury Night", "VIP Event", "Self-Care Day", "Home Spa", "Staycation",
    "Content Shoot", "Influencer Edit", "Runway Ready", "TV Ready", "Camera Friendly",
    "Long Shift", "Quick Routine", "Touch-Up Kit", "Weekend Trip", "Road Trip",
    "Seasonal Glow", "Limited Drop", "Launch Day", "Holiday Gift", "Giftable",
    "Stocking Stuffer", "Signature Event", "Special Edition"
]

BENEFITS = [
    "Hydrating", "Deep Hydration", "Oil Control", "Brightening", "Firming",
    "Smoothing", "Plumping", "Balancing", "Calming", "Long-Lasting",
    "Buildable", "Transfer-Resistant", "Sweat-Resistant", "Water-Resistant",
    "Humidity Shield", "Pore Blurring", "Fine Line Smoothing", "Elasticity Boost",
    "Collagen Support", "Glow Enhancing", "Tone Correcting", "Texture Refining",
    "Barrier Repair", "Barrier Support", "Soothing", "Cooling", "Refreshing",
    "Lightweight Feel", "Non-Greasy", "Non-Sticky", "Quick Absorb", "Fast Dry",
    "Layer Friendly", "Makeup Friendly", "SPF Support", "UV Protection",
    "Blue Light Shield", "Pollution Defense", "Detoxifying", "Clarifying",
    "Purifying", "Exfoliating", "Gentle", "Sensitive Safe", "Derm Tested",
    "Clean Formula", "Vegan Friendly", "Cruelty Free", "Paraben Free",
    "Sulphate Free", "Silicone Free", "Fragrance Light", "High Pigment",
    "Soft Pigment", "Gloss Boost", "Volume Boost", "Curl Boost", "Length Boost",
    "Strengthening", "Repairing", "Nourishing", "Moisture Lock", "Shine Boost",
    "Glow Lock", "Flexible Hold", "Strong Hold", "Soft Hold", "Flake-Free",
    "Fade Resistant", "Smudge Resistant", "Feather Light", "Grip Boost",
    "Smooth Glide", "Quick Style", "Heat Protect", "Damage Control",
    "Split-End Care", "Scalp Friendly", "Hydro Boost"
]

ROUTINE_STEPS = [
    "Morning", "Night", "AM Routine", "PM Routine", "Daily Essential", "Prep Step",
    "Prime", "Treat", "Seal", "Refresh", "Boost", "Hydrate", "Tone", "Cleanse",
    "Exfoliate", "Mask", "Target", "Repair", "Protect", "SPF Layer", "Glow Boost",
    "Finish Step", "Setting Step", "On-The-Go", "Travel", "Gym Ready",
    "Post-Workout", "Desk Refresh", "Event Prep", "Pre-Makeup", "Post-Makeup",
    "Recovery", "Reset", "Weekend Routine", "Self-Care", "Deep Care",
    "Express Care", "Full Routine", "Minimal Routine", "Layer 1", "Layer 2",
    "Layer 3", "Final Step", "Touch-Up", "Midday Refresh", "Evening Repair",
    "Overnight Care", "Barrier Support", "Glow Layer", "Moisture Lock",
    "Oil Balance", "Texture Smooth", "Radiance Boost", "Firming Step",
    "Plump Step", "Calm Step", "Clarify", "Brighten", "Detox", "Replenish",
    "Restore"
]

TEXTURES = [
    "Silky", "Velvety", "Lightweight", "Ultra-Light", "Creamy", "Rich Cream",
    "Whipped", "Airy", "Bouncy", "Gel", "Soft Gel", "Water Gel", "Serum-Light",
    "Fluid", "Lotion", "Milky", "Satin Smooth", "Glossy", "Sheer", "Powdery",
    "Mousse", "Cloud-Like", "Dense", "Featherlight", "Oil-Infused",
    "Fast-Absorbing", "Quick-Dry", "Non-Sticky", "Weightless", "Luxurious",
    "Soft Touch", "Cooling", "Refreshing", "Hydro-Burst", "Elastic", "Plush",
    "Flexible", "Buttery", "Slip-Finish", "Glide-On", "Melting", "Cushiony",
    "Smooth Spread", "Grip-Prime", "Fine Mist", "Micro-Mist", "Dry Touch",
    "Second-Skin", "Comfort Wear", "Stretch-Fit", "Seamless"
]

FINISHES = [
    "Natural Glow", "Radiant", "Dewy", "Glass Skin", "Soft Matte", "Velvet Matte",
    "Satin", "Luminous", "Sheer Glow", "High Shine", "Glossy", "Blurred",
    "Soft Blur", "Filtered Finish", "Airbrushed", "Barely-There", "Fresh Finish",
    "Healthy Glow", "Lit-From-Within", "Glow Boost", "Light Reflecting",
    "Illuminated", "Skin-Like", "Flawless", "Polished", "Clean Finish",
    "Silk Finish", "Smooth Finish", "Matte Control", "Shine-Free", "Hydra-Glow",
    "Reflective", "Velvet Skin", "Creamy Matte", "Modern Matte", "Soft Focus",
    "Bright Finish", "Natural Matte", "Long-Wear Matte", "Radiant Matte",
    "Glow Lock", "Crystal Glow", "Bare Skin", "Second-Skin", "Soft Radiance",
    "Velvet Blur", "Pure Glow", "Demi-Matte", "Skin Veil", "Luxury Matte",
    "Halo Glow", "Diffused", "Balanced Finish", "Air Glow", "Glam Glow",
    "Runway Finish", "Subtle Shine", "Golden Glow", "Bronzed Glow", "Studio Finish"
]

SKIN_PROFILE = [
    "All Skin", "Normal", "Dry", "Very Dry", "Oily", "Very Oily", "Combination",
    "Sensitive", "Reactive", "Acne-Prone", "Hormonal", "Mature", "Teen",
    "Post-Treatment", "Redness-Prone", "Uneven Tone", "Textured", "Dull",
    "Dehydrated", "Sun-Exposed", "Balanced", "Resilient", "Fragile", "Irritated",
    "Stressed", "Urban Skin", "Pollution-Exposed", "Barrier-Compromised",
    "Elasticity Loss", "Fine Lines", "Deep Lines", "Dark Spot Concern",
    "Hyperpigmentation", "Large Pores", "Congested", "T-Zone Oily", "Flaky",
    "Rough", "Tight", "Over-Exfoliated","combination",
    "balanced", "normal", "sensitive", "reactive", "acne-prone",
    "blemish-prone", "dehydrated", "moisture-depleted", "tight-feeling",
    "flaky", "parched", "shine-prone", "sebum-rich",
    "oil-balanced", "matte-prone", "t-zone-oily", "u-zone-dry",
    "easily irritated", "redness-prone", "rosacea-prone", "fragile",
    "delicate", "rough-textured", "uneven-textured", "smooth-textured", "refined-texture",
    "enlarged-pores", "clogged-pores", "bumpy-skin", "dull", "brightness-seeking",
    "hyperpigmentation-prone", "dark-spot-prone", "uneven-tone", "radiance-seeking",
    "mature", "pre-mature-aging", "fine-line-prone", "loss-of-firmness",
    "elasticity-depleted", "barrier-compromised", "barrier-weakened", "barrier-damaged",
]

BUSINESS_TIERS = [
    "Core", "Hero", "Premium", "Elite", "Signature", "Limited", "Seasonal",
    "Best Seller", "Top Rated", "Editor Pick", "Influencer Pick", "New Arrival",
    "Trending", "Featured", "Spotlight", "Collection Star", "High Demand",
    "Fast Moving", "Boutique Select", "Curated Pick", "Launch Drop", "VIP Edit",
    "Luxury Tier", "Accessible Luxury", "Entry Luxe", "High Margin",
    "Upsell Anchor", "Bundle Ready", "Gift Ready", "Routine Builder",
    "Add-On Favorite", "Cross-Sell Hero", "AOV Booster", "High Visibility",
    "Priority SKU", "Evergreen", "Restock Alert", "Low Stock", "Exclusive",
    "Private Label", "MVQueen Exclusive", "Online Only", "Limited Batch",
    "Rare Find", "Premium Blend", "Advanced Formula", "Pro Level", "Studio Level",
    "Runway Level", "Backstage Approved", "Retail Favorite", "Flagship",
    "Anchor Product", "Core Essential", "Glow Essential", "Must Have",
    "Signature SKU", "Daily Favorite", "Rising Star", "High Conversion",
    "Strong Performer", "Stable Seller", "Seasonal Hero", "Limited Run",
    "Collector", "Elevated Edition", "Refined Formula", "Enhanced", "Version 2",
    "Reformulated", "Improved", "Next Gen", "Future Glow", "Advanced Glow",
    "Icon Status", "Hall of Fame", "Classic", "Timeless Essential",
    "Luxe Upgrade", "Power Product"
]

SEO_PRIMARY = [
     "luxury fashion", "premium apparel", "designer essentials",
    "elevated basics", "modern wardrobe", "quiet luxury style",
    "editorial fashion", "minimalist fashion", "street luxe style",    "luxury skincare", "clean beauty", "glowing skin", "hydrating serum",
    "anti-aging routine", "brightening formula", "soft glam makeup",
    "long-wear foundation", "dewy finish", "glass skin routine",
    "matte finish makeup", "sensitive skin safe", "vegan beauty",
    "cruelty-free skincare", "editorial fashion", "runway beauty",
    "quiet luxury outfits", "street style fashion", "minimalist wardrobe",
    "capsule collection essentials",
]

SEO_SECONDARY = [
    "luxury essentials", "premium quality", "modern wardrobe staples",
    "elevated everyday style", "designer-inspired looks", "quiet luxury outfits",
    "minimalist fashion trends", "street luxe aesthetic", "editorial-inspired styling",
    "high-end beauty essentials", "glowing skin routine",
    "hydrating skincare favorites", "soft glam makeup looks", "romantic feminine style",
     "resort-ready fashion", "daily moisturizer", "skin barrier repair", "SPF protection",
    "lightweight foundation", "soft matte look", "hydrating lip gloss",
    "long-lasting wear", "buildable coverage", "natural glow",
    "even skin tone", "texture smoothing", "fine line care",
    "clean girl aesthetic", "soft glam routine", "night-out makeup",
    "event-ready glam", "vacation outfits", "date night looks",
    "elevated basics", "premium fabrics",
]

COLLECTION_TYPE = [
    "Category", "Product Type", "Persona", "Trend", "Season",
    "Benefit", "Routine", "Fashion", "SEO", "Occasion", 
    "Mood","dresses", "tops", "bottoms", "outerwear" "knitwear", "activewear", "loungewear",
    "swimwear","denim", "footwear", "accessories",
    "minimalist edit", "quiet luxury", "evening edit",
    "streetwear edit", "capsule wardrobe", "spring refresh",
    "summer essentials", "fall layers", "winter luxe",
    "holiday edit", "silk edit", "linen edit", "oversized fits",
    "tailored fits", "romantic vibe", "edgy vibe",
    "classic vibe", "neutral palette", "bold color edit", "Vibe",
     "Material", "Silhouette", "Detail", "Benefit",
    "Routine", "Category", "Product Type", "Persona", "Trend",
    "Season", "Fashion", "SEO", "Occasion", "Mood"
]

TREND_KEYWORDS = [
    "quiet luxury", "soft glam", "clean girl", "street luxe",
    "editorial chic", "resort chic", "CEO energy", "vacation mode",
    "old money", "new money glam", "minimalist", "maximalist",
    "romantic feminine", "athleisure luxe"
]

SEASON_KEYWORDS = [
    "spring", "summer", "fall", "winter", "holiday", "resort"
]

SKINCARE_PRODUCT_TYPES = [
    # --- Cleansers ---
    "cleanser",
    "gel cleanser",
    "cream cleanser",
    "foam cleanser",
    "oil cleanser",
    "balm cleanser",
    "micellar water",
    "exfoliating cleanser",
    "enzyme cleanser",

    # --- Exfoliators ---
    "exfoliator",
    "chemical exfoliant",
    "aha exfoliant",
    "bha exfoliant",
    "pha exfoliant",
    "enzyme exfoliant",
    "scrub",
    "polish",
    "resurfacing treatment",

    # --- Toners / Essences ---
    "toner",
    "hydrating toner",
    "exfoliating toner",
    "essence",
    "treatment essence",
    "skin softener",
    "lotion essence",

    # --- Serums ---
    "serum",
    "hydrating serum",
    "brightening serum",
    "vitamin c serum",
    "niacinamide serum",
    "retinol serum",
    "aha serum",
    "bha serum",
    "peptide serum",
    "hyaluronic acid serum",
    "anti-aging serum",
    "pore-refining serum",
    "acne serum",
    "soothing serum",
    "barrier serum",

    # --- Ampoules / Boosters ---
    "ampoule",
    "booster",
    "treatment booster",
    "concentrate",

    # --- Moisturizers ---
    "moisturizer",
    "gel moisturizer",
    "cream moisturizer",
    "rich cream",
    "water cream",
    "balm moisturizer",
    "whipped moisturizer",
    "oil-free moisturizer",
    "barrier cream",
    "night cream",
    "sleeping mask",

    # --- Oils ---
    "face oil",
    "treatment oil",
    "dry oil",
    "nourishing oil",
    "cleansing oil",

    # --- Masks ---
    "mask",
    "sheet mask",
    "clay mask",
    "mud mask",
    "gel mask",
    "overnight mask",
    "peel-off mask",
    "enzyme mask",
    "exfoliating mask",
    "hydrating mask",
    "brightening mask",

    # --- Eye Care ---
    "eye cream",
    "eye serum",
    "eye gel",
    "eye balm",
    "brightening eye cream",
    "firming eye cream",

    # --- Lip Care ---
    "lip balm",
    "lip mask",
    "lip treatment",
    "lip oil",
    "lip exfoliator",

    # --- Mists ---
    "face mist",
    "hydrating mist",
    "setting mist",
    "soothing mist",

    # --- Sunscreen ---
    "sunscreen",
    "spf moisturizer",
    "mineral sunscreen",
    "chemical sunscreen",
    "tinted sunscreen",
    "sun gel",
    "sun milk",

    # --- Spot Treatments ---
    "spot treatment",
    "acne spot treatment",
    "dark spot treatment",
    "blemish treatment",

    # --- Retinol / Actives ---
    "retinol treatment",
    "retinoid treatment",
    "acid treatment",
    "aha treatment",
    "bha treatment",
    "resurfacing treatment",

    # --- Tools / Devices ---
    "gua sha",
    "jade roller",
    "facial roller",
    "cleansing device",
    "led mask",
    "microcurrent device",

    # --- Body Skincare ---
    "body lotion",
    "body cream",
    "body butter",
    "body oil",
    "body serum",
    "body exfoliant",
    "body scrub",
    "body wash",
    "kp treatment",
    "ingrown treatment",

    # --- Persona-Based Product Types ---
    "soft luxury skincare",
    "clinical skincare",
    "runway skincare",
    "street luxe skincare",
    "old money skincare",
    "glow maestro skincare",

    # --- Marketing-Friendly Product Types ---
    "barrier repair treatment",
    "glow treatment",
    "hydration treatment",
    "firming treatment",
    "radiance treatment",
    "pore treatment",
    "clarifying treatment"
]

