#!/bin/bash
VAULT="$HOME/storage/shared/MVQUEEN_OS"
OUTPUT="$HOME/storage/shared/MVQUEEN_OS/MVQUEEN_CONTEXT.md"
echo "👑 MVQUEEN_OS — Full Context Pull v2"
EMPTY=0; POPULATED=0; MISSING=0; REBUILT=0
echo "# MVQUEEN_OS SESSION CONTEXT" > "$OUTPUT"
echo "Brand: MVQUEEN | Sister: Miss.Princess | Phase 1-2 COMPLETE | Phase 3 IN PROGRESS" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
pull_file() {
  local FILE="$1"
  local FULL="$VAULT/$FILE"
  echo "" >> "$OUTPUT"
  echo "---" >> "$OUTPUT"
  echo "### FILE: $FILE" >> "$OUTPUT"
  if [ ! -f "$FULL" ]; then
    echo "**STATUS: MISSING**" >> "$OUTPUT"
    echo "⚠️  MISSING: $FILE"; MISSING=$((MISSING+1)); return
  fi
  SIZE=$(wc -c < "$FULL"); LINES=$(wc -l < "$FULL")
  IS_REBUILT=$(head -3 "$FULL" | grep -c "MVQUEEN" 2>/dev/null || echo 0)
  if [ "$SIZE" -lt 100 ]; then
    echo "**STATUS: EMPTY**" >> "$OUTPUT"
    echo "🔴 EMPTY: $FILE"; EMPTY=$((EMPTY+1))
  elif [ "$IS_REBUILT" -gt 0 ]; then
    echo "**STATUS: REBUILT — $SIZE bytes**" >> "$OUTPUT"
    echo "✅ REBUILT: $FILE"; REBUILT=$((REBUILT+1)); POPULATED=$((POPULATED+1))
  else
    echo "**STATUS: POPULATED — $SIZE bytes**" >> "$OUTPUT"
    echo "📄 POPULATED: $FILE"; POPULATED=$((POPULATED+1))
  fi
  cat "$FULL" >> "$OUTPUT"; echo "" >> "$OUTPUT"
}
pull_file "00_Doctrine/master_doctrine.md"
pull_file "00_Doctrine/brand_constitution.md"
pull_file "00_Doctrine/luxury_philosophy.md"
pull_file "00_Doctrine/ai_governance.md"
pull_file "01_Brand_Strategy/Brand_Bible.md"
pull_file "01_Brand_Strategy/USP.md"
pull_file "01_Brand_Strategy/Elevator_Pitch.md"
pull_file "01_Brand_Strategy/Slogans.md"
pull_file "01_Brand_Strategy/Taglines.md"
pull_file "01_Brand_Strategy/Brand_Essence.md"
pull_file "01_Brand_Strategy/Brand_Positioning.md"
pull_file "01_Brand_Strategy/Brand_Story.md"
pull_file "01_Brand_Strategy/Brand_Values.md"
pull_file "01_Brand_Strategy/Mission_And_Vision.md"
pull_file "01_Brand_Strategy/brand_manifesto.md"
pull_file "02_Brand_Identity/color_system.md"
pull_file "02_Brand_Identity/typography_system.md"
pull_file "02_Brand_Identity/brand_rules.md"
pull_file "02_Brand_Identity/visual_direction.md"
pull_file "02_Brand_Identity/packaging_identity.md"
pull_file "02_Brand_Identity/photography_direction.md"
pull_file "03_Customer_Psychology/Customer_Personas.md"
pull_file "03_Customer_Psychology/customer_objections.md"
pull_file "03_Customer_Psychology/trust_building.md"
pull_file "03_Customer_Psychology/emotional_drivers.md"
pull_file "03_Customer_Psychology/Buying_Psychology.md"
pull_file "04_Products/Product_Naming_System.md"
pull_file "04_Products/Pricing_Strategy.md"
pull_file "04_Products/Collection_Structure.md"
pull_file "04_Products/Product_Framework.md"
pull_file "04_Products/Product_Catalog.md"
pull_file "04_Products/Beauty_Products.md"
pull_file "04_Products/Fashion_Products.md"
pull_file "04_Products/Hair_Products.md"
pull_file "04_Products/SKU_Systems.md"
pull_file "05_SEO_And_Content/SEO_Strategy.md"
pull_file "05_SEO_And_Content/Blog_Strategy.md"
pull_file "05_SEO_And_Content/Content_Calendar.md"
pull_file "05_SEO_And_Content/Keyword_Research.md"
pull_file "06_Tone_And_Voice/Forbidden_Words.md"
pull_file "06_Tone_And_Voice/Voice_Consistency_Rules.md"
pull_file "06_Tone_And_Voice/Writing_Rules.md"
pull_file "06_Tone_And_Voice/CTA_Library.md"
pull_file "06_Tone_And_Voice/Example_Copy.md"
pull_file "06_Tone_And_Voice/Product_Description_Voice.md"
pull_file "06_Tone_And_Voice/Hook_Systems.md"
pull_file "06_Tone_And_Voice/Tone_Guide.md"
pull_file "06_Tone_And_Voice/Brand_Messaging.md"
pull_file "06_Tone_And_Voice/Ad_Copy_Voice.md"
pull_file "06_Tone_And_Voice/Email_Voice.md"
pull_file "06_Tone_And_Voice/Social_Voice.md"
pull_file "06_Tone_And_Voice/SMS_Voice.md"
pull_file "08_Social_Media/Content_Pillars.md"
pull_file "08_Social_Media/Caption_Templates.md"
pull_file "08_Social_Media/Instagram_Strategy.md"
pull_file "08_Social_Media/TikTok_Strategy.md"
pull_file "08_Social_Media/Pinterest_Strategy.md"
pull_file "10_AI_Systems/AI_Prompt_Library.md"
pull_file "10_AI_Systems/Product_Description_Prompts.md"
pull_file "10_AI_Systems/Ad_Copy_Prompts.md"
pull_file "10_AI_Systems/Image_Generation_Prompts.md"
pull_file "10_AI_Systems/Social_Media_Prompts.md"
echo "" >> "$OUTPUT"
echo "## PULL SUMMARY" >> "$OUTPUT"
echo "- Rebuilt: $REBUILT" >> "$OUTPUT"
echo "- Populated: $((POPULATED-REBUILT))" >> "$OUTPUT"
echo "- Empty: $EMPTY" >> "$OUTPUT"
echo "- Missing: $MISSING" >> "$OUTPUT"
echo "- Timestamp: $(date)" >> "$OUTPUT"
echo "======================================"
echo "✅ DONE — Rebuilt: $REBUILT | Empty: $EMPTY | Missing: $MISSING"
echo "📤 Upload MVQUEEN_CONTEXT.md to Claude"
echo "======================================"
